<?php
declare(strict_types=1);

/** Dataset — Referências Primárias (autores diretamente utilizados por Freud e Lacan). */

return [
    ['nome' => 'Platão', 'vida' => 'c. 428/427–348/347 a.C.', 'nacionalidade' => 'Grego (Atenas)', 'area' => 'Filosofia',
        'vinculo' => 'Fonte indireta: Lacan comenta O Banquete extensamente no Seminário VIII (A Transferência) para articular o amor de transferência e o objeto a.',
        'conceitos' => ['Eros', 'Mito', 'Diálogo filosófico'], 'autores_relacionados' => ['Aristóteles', 'Sócrates'],
        'obras_relacionadas' => ['A Transferência (Seminário VIII)'], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Aristóteles', 'vida' => '384–322 a.C.', 'nacionalidade' => 'Grego (Estagira)', 'area' => 'Filosofia',
        'vinculo' => 'O conceito aristotélico de catarse (Poética) precede e informa o "método catártico" de Estudos sobre a Histeria; a Ética a Nicômaco é pano de fundo do Seminário VII de Lacan (A Ética da Psicanálise).',
        'conceitos' => ['Catarse', 'Causa', 'Ética'], 'autores_relacionados' => ['Platão'],
        'obras_relacionadas' => ['Estudos sobre a Histeria', 'A Ética da Psicanálise (Seminário VII)'], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Sócrates', 'vida' => 'c. 470–399 a.C.', 'nacionalidade' => 'Grego (Atenas)', 'area' => 'Filosofia',
        'vinculo' => 'Referência explícita e nomeada de Documento-Mestre.md §6.7: o modo de enunciação do PsycheAI adota o método socrático (maiêutica) — não a figura histórica, mas o método de provocar a associação livre sem entregar conteúdo, causa ou sentido no lugar do sujeito.',
        'conceitos' => ['Maiêutica', 'Ironia socrática', 'Elenchos'], 'autores_relacionados' => ['Platão'],
        'obras_relacionadas' => [], 'motores' => ['Modo Socrático'],
        'status' => 'Catalogado', 'observacoes' => 'Único autor de Referências Primárias com motor do PsycheAI já vinculado por nome em Documento-Mestre.md — não uma obra escrita por Sócrates (não deixou textos próprios), mas o método a ele atribuído via os diálogos platônicos.'],
    ['nome' => 'René Descartes', 'vida' => '1596–1650', 'nacionalidade' => 'Francês', 'area' => 'Filosofia',
        'vinculo' => 'O cogito cartesiano é o ponto de partida da leitura lacaniana do "sujeito da ciência" (Écrits, "Science et vérité") — o sujeito dividido ($) de Lacan se define em relação crítica ao sujeito cartesiano.',
        'conceitos' => ['Cogito', 'Dúvida metódica', 'Sujeito da ciência'], 'autores_relacionados' => ['Jacques Lacan'],
        'obras_relacionadas' => ['Ciência e Verdade'], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Immanuel Kant', 'vida' => '1724–1804', 'nacionalidade' => 'Alemão (Prússia)', 'area' => 'Filosofia',
        'vinculo' => 'Objeto direto do ensaio "Kant avec Sade" de Lacan, que confronta o imperativo categórico kantiano com a obra do Marquês de Sade para pensar a ética do desejo.',
        'conceitos' => ['Imperativo categórico', 'Lei moral', 'Dever'], 'autores_relacionados' => ['Marquês de Sade'],
        'obras_relacionadas' => ['Kant com Sade'], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Georg Wilhelm Friedrich Hegel', 'vida' => '1770–1831', 'nacionalidade' => 'Alemão', 'area' => 'Filosofia',
        'vinculo' => 'A dialética do senhor e do escravo (Fenomenologia do Espírito), lida por Lacan sobretudo através do curso de Alexandre Kojève, fundamenta a noção lacaniana de desejo como desejo de reconhecimento.',
        'conceitos' => ['Dialética do senhor e do escravo', 'Reconhecimento', 'Negatividade'], 'autores_relacionados' => ['Alexandre Kojève'],
        'obras_relacionadas' => [], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Søren Kierkegaard', 'vida' => '1813–1855', 'nacionalidade' => 'Dinamarquês', 'area' => 'Filosofia',
        'vinculo' => 'Autor de A Repetição (1843), obra filosófica que antecede e ressoa com o conceito psicanalítico de repetição, embora com estatuto teórico distinto (existencial, não pulsional).',
        'conceitos' => ['Repetição', 'Angústia', 'Existência'], 'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => ['Além do Princípio do Prazer'], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => 'A obra homônima de Kierkegaard (A Repetição) não deve ser confundida com o conceito freudiano de mesmo nome — tratam-se de repertórios teóricos distintos, não fundidos nesta Biblioteca.'],
    ['nome' => 'Friedrich Nietzsche', 'vida' => '1844–1900', 'nacionalidade' => 'Alemão', 'area' => 'Filosofia',
        'vinculo' => 'Influência reconhecida por Freud (com reservas explícitas sobre prioridade de ideias) sobre a noção de pulsão e de forças inconscientes atuando por trás da consciência; o eterno retorno dialoga de longe com a compulsão à repetição.',
        'conceitos' => ['Vontade de poder', 'Eterno retorno', 'Pulsão'], 'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => ['Além do Princípio do Prazer'], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Martin Heidegger', 'vida' => '1889–1976', 'nacionalidade' => 'Alemão', 'area' => 'Filosofia',
        'vinculo' => 'Interlocutor direto de Lacan, que traduziu o ensaio "Logos" de Heidegger para o francês; a noção de verdade como desvelamento (alétheia) informa a leitura lacaniana da verdade que "fala" no sintoma.',
        'conceitos' => ['Ser-aí (Dasein)', 'Verdade como desvelamento (alétheia)', 'Linguagem'], 'autores_relacionados' => ['Jacques Lacan'],
        'obras_relacionadas' => [], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Alexandre Kojève', 'vida' => '1902–1968', 'nacionalidade' => 'Russo-francês', 'area' => 'Filosofia',
        'vinculo' => 'Seu curso sobre a Fenomenologia do Espírito de Hegel (École Pratique des Hautes Études, 1933–1939), frequentado por parte da geração intelectual francesa da época, é a via de acesso mais direta de Lacan à dialética hegeliana do desejo e do reconhecimento.',
        'conceitos' => ['Desejo de reconhecimento', 'Dialética hegeliana', 'Fim da história'], 'autores_relacionados' => ['Georg Wilhelm Friedrich Hegel', 'Jacques Lacan'],
        'obras_relacionadas' => [], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Baruch de Spinoza', 'vida' => '1632–1677', 'nacionalidade' => 'Neerlandês', 'area' => 'Filosofia',
        'vinculo' => 'Referência filosófica de fundo para a teoria dos afetos, ocasionalmente retomada na tradição psicanalítica francesa em discussões sobre afeto e causa.',
        'conceitos' => ['Afeto', 'Conatus'], 'autores_relacionados' => [],
        'obras_relacionadas' => [], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Blaise Pascal', 'vida' => '1623–1662', 'nacionalidade' => 'Francês', 'area' => 'Filosofia',
        'vinculo' => 'A "aposta de Pascal" (Pensées) é uma referência ocasional na tradição lógico-filosófica que Lacan mobiliza em discussões sobre certeza e decisão sob incerteza (cf. "O Tempo Lógico e a Asserção de Certeza Antecipada").',
        'conceitos' => ['Aposta de Pascal', 'Razão e coração'], 'autores_relacionados' => ['Jacques Lacan'],
        'obras_relacionadas' => ['O Tempo Lógico e a Asserção de Certeza Antecipada'], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Ferdinand de Saussure', 'vida' => '1857–1913', 'nacionalidade' => 'Suíço', 'area' => 'Linguística',
        'vinculo' => 'O Curso de Linguística Geral (publicado postumamente por seus alunos, 1916) funda a linguística estrutural; Lacan inverte a relação significante/significado do signo saussuriano para formular sua tese "o inconsciente é estruturado como uma linguagem".',
        'conceitos' => ['Signo linguístico', 'Significante', 'Significado', 'Langue e parole'], 'autores_relacionados' => ['Jacques Lacan', 'Roman Jakobson'],
        'obras_relacionadas' => ['A Instância da Letra no Inconsciente ou a Razão desde Freud'], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => 'Fonte direta do vocabulário de "significante" e "cadeia significante" de Ontologia-Lacan.md §3, ainda que o próprio Saussure não seja autor citado nominalmente naquele documento nesta versão.'],
    ['nome' => 'Roman Jakobson', 'vida' => '1896–1982', 'nacionalidade' => 'Russo-americano', 'area' => 'Linguística',
        'vinculo' => 'Sua teoria dos eixos metafórico (seleção/similaridade) e metonímico (combinação/contiguidade) da linguagem é a fonte estrutural direta da equivalência lacaniana condensação=metáfora / deslocamento=metonímia.',
        'conceitos' => ['Metáfora', 'Metonímia', 'Funções da linguagem', 'Eixo paradigmático e sintagmático'], 'autores_relacionados' => ['Ferdinand de Saussure', 'Jacques Lacan'],
        'obras_relacionadas' => ['A Instância da Letra no Inconsciente ou a Razão desde Freud'], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => 'Fonte estrutural direta da tabela de releitura Condensação→Metáfora / Deslocamento→Metonímia citada em Ontologia-Lacan.md §4 e usada por ReclassificadorLacaniano (ver Como-os-Motores-Usam-a-Biblioteca.md).'],
    ['nome' => 'Émile Benveniste', 'vida' => '1902–1976', 'nacionalidade' => 'Francês', 'area' => 'Linguística',
        'vinculo' => 'Problemas de Linguística Geral (1966) desenvolve a teoria da enunciação e da subjetividade na linguagem, relevante para a distinção lacaniana entre enunciado e enunciação.',
        'conceitos' => ['Enunciação', 'Subjetividade na linguagem', 'Aparelho formal da enunciação'], 'autores_relacionados' => ['Ferdinand de Saussure'],
        'obras_relacionadas' => [], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Claude Lévi-Strauss', 'vida' => '1908–2009', 'nacionalidade' => 'Francês', 'area' => 'Antropologia',
        'vinculo' => 'As Estruturas Elementares do Parentesco (1949) retoma e reformula estruturalmente a proibição do incesto tratada por Freud em Totem e Tabu; o estruturalismo antropológico de Lévi-Strauss é interlocutor direto do estruturalismo lacaniano.',
        'conceitos' => ['Estruturalismo', 'Troca simbólica', 'Proibição do incesto'], 'autores_relacionados' => ['Sigmund Freud', 'Jacques Lacan'],
        'obras_relacionadas' => ['Totem e Tabu'], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Jean-Martin Charcot', 'vida' => '1825–1893', 'nacionalidade' => 'Francês', 'area' => 'Psiquiatria/Neurologia',
        'vinculo' => 'Neurologista da Salpêtrière (Paris) sob quem Freud estudou em 1885–1886; suas demonstrações clínicas sobre hipnose e histeria são o ponto de partida biográfico e teórico do interesse de Freud pelas neuroses.',
        'conceitos' => ['Hipnose', 'Histeria', 'Sugestão'], 'autores_relacionados' => ['Sigmund Freud', 'Pierre Janet'],
        'obras_relacionadas' => ['Charcot'], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Josef Breuer', 'vida' => '1842–1925', 'nacionalidade' => 'Austríaco', 'area' => 'Psiquiatria/Neurologia',
        'vinculo' => 'Coautor de Estudos sobre a Histeria (1895) com Freud; o tratamento do caso "Anna O." desenvolvido por Breuer é o precedente clínico direto do método catártico.',
        'conceitos' => ['Catarse', 'Método catártico', 'Estado hipnoide'], 'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => ['Estudos sobre a Histeria'], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => 'Coautor listado também nas obras correspondentes em Freud/Obras/.'],
    ['nome' => 'Pierre Janet', 'vida' => '1859–1947', 'nacionalidade' => 'Francês', 'area' => 'Psiquiatria/Neurologia',
        'vinculo' => 'Contemporâneo e, em certa medida, rival teórico de Freud; sua teoria da dissociação psíquica (désagrégation) e do automatismo psicológico antecede e dialoga com a teoria freudiana do inconsciente.',
        'conceitos' => ['Dissociação psíquica', 'Automatismo psicológico'], 'autores_relacionados' => ['Jean-Martin Charcot', 'Sigmund Freud'],
        'obras_relacionadas' => [], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Wilhelm Fliess', 'vida' => '1858–1928', 'nacionalidade' => 'Alemão', 'area' => 'Psiquiatria/Neurologia',
        'vinculo' => 'Otorrinolaringologista berlinense, correspondente e principal interlocutor teórico de Freud entre 1887 e 1904; destinatário do "Rascunho de uma Psicologia Científica" e de grande parte da correspondência em que Freud elabora as primeiras hipóteses psicanalíticas.',
        'conceitos' => ['Bissexualidade', 'Periodicidade biológica'], 'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => ['Rascunho de uma Psicologia Científica'], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => 'Não é médico especializado em psiquiatria/neurologia stricto sensu (é otorrinolaringologista) — classificado aqui por proximidade de área e por ser o interlocutor clínico-teórico do período fundacional, conforme a lista da Sprint.'],
    ['nome' => 'William Shakespeare', 'vida' => '1564–1616', 'nacionalidade' => 'Inglês', 'area' => 'Literatura',
        'vinculo' => 'Hamlet é referência recorrente em Freud (A Interpretação dos Sonhos) e objeto de leitura extensa por Lacan (seminário sobre o desejo em Hamlet, 1958–1959, parte do Seminário VI).',
        'conceitos' => ['Hamlet', 'Tragédia', 'Desejo'], 'autores_relacionados' => ['Sigmund Freud', 'Jacques Lacan'],
        'obras_relacionadas' => ['A Interpretação dos Sonhos', 'O Desejo e sua Interpretação (Seminário VI)'], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Sófocles', 'vida' => 'c. 497/496–406/405 a.C.', 'nacionalidade' => 'Grego (Atenas)', 'area' => 'Literatura',
        'vinculo' => 'Édipo Rei dá nome ao complexo de Édipo freudiano; Antígona é lida extensamente por Lacan no Seminário VII (A Ética da Psicanálise) como paradigma ético do desejo.',
        'conceitos' => ['Complexo de Édipo', 'Tragédia', 'Ética do desejo'], 'autores_relacionados' => ['Sigmund Freud', 'Jacques Lacan'],
        'obras_relacionadas' => ['A Ética da Psicanálise (Seminário VII)'], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Homero', 'vida' => 'Datação incerta, tradicionalmente c. século VIII a.C.', 'nacionalidade' => 'Grego (autoria tradicional)', 'area' => 'Literatura',
        'vinculo' => 'Referência ocasional de fundo (Ilíada, Odisseia) na tradição literária mobilizada por Freud e por comentadores da psicanálise em discussões sobre mito e narrativa.',
        'conceitos' => ['Épica', 'Mito'], 'autores_relacionados' => [],
        'obras_relacionadas' => [], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'A verificar', 'observacoes' => 'Autoria e datação da obra homérica são objeto de disputa filológica não resolvida ("questão homérica") — mantido aqui como referência tradicional, não como fato biográfico verificável.'],
    ['nome' => 'Johann Wolfgang von Goethe', 'vida' => '1749–1832', 'nacionalidade' => 'Alemão', 'area' => 'Literatura',
        'vinculo' => 'Freud recebeu o Prêmio Goethe em 1930; referências a Fausto aparecem ao longo da obra freudiana como repertório cultural comum da formação de Freud.',
        'conceitos' => ['Fausto', 'Formação (Bildung)'], 'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => [], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'James Joyce', 'vida' => '1882–1941', 'nacionalidade' => 'Irlandês', 'area' => 'Literatura',
        'vinculo' => 'Objeto central do Seminário XXIII de Lacan (O Sinthoma) e da conferência "Joyce, o Sintoma" — a escrita de Joyce (sobretudo Finnegans Wake) é lida como suplência ao Nome-do-Pai.',
        'conceitos' => ['Sinthoma', 'Escrita', 'Equívoco', 'Suplência'], 'autores_relacionados' => ['Jacques Lacan'],
        'obras_relacionadas' => ['O Sinthoma (Seminário XXIII)', 'Joyce, o Sintoma', 'Lituraterra'], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Fiódor Dostoiévski', 'vida' => '1821–1881', 'nacionalidade' => 'Russo', 'area' => 'Literatura',
        'vinculo' => 'Objeto do ensaio "Dostoiévski e o Parricídio" de Freud, que lê Os Irmãos Karamázov à luz da ambivalência edípica e da culpa inconsciente.',
        'conceitos' => ['Parricídio', 'Culpa inconsciente', 'Ambivalência'], 'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => ['Dostoiévski e o Parricídio'], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Edgar Allan Poe', 'vida' => '1809–1849', 'nacionalidade' => 'Norte-americano', 'area' => 'Literatura',
        'vinculo' => 'Autor do conto "A Carta Roubada", comentado por Lacan em "O Seminário sobre \'A Carta Roubada\'" (abertura de Écrits, 1966) para ilustrar a circulação do significante e a repetição automática.',
        'conceitos' => ['A Carta Roubada', 'Repetição automática'], 'autores_relacionados' => ['Jacques Lacan'],
        'obras_relacionadas' => ['O Seminário sobre "A Carta Roubada"'], 'motores' => ['Nenhum (catalogação apenas)'],
        'status' => 'Catalogado', 'observacoes' => ''],
];
