<?php
declare(strict_types=1);

/** Dataset — autores da tradição psicanalítica pós-freudiana/pós-lacaniana listados na Sprint da Biblioteca Teórica. */

return [
    ['nome' => 'Melanie Klein', 'vida' => '1882–1960', 'nacionalidade' => 'Austro-britânica', 'area' => 'Psicanálise',
        'vinculo' => 'Pioneira da psicanálise de crianças; suas divergências teóricas e institucionais com Anna Freud (as "Controvérsias" na Sociedade Britânica de Psicanálise, década de 1940) marcam uma das principais bifurcações pós-freudianas.',
        'conceitos' => ['Objeto parcial', 'Posição esquizoparanoide', 'Posição depressiva', 'Inveja'],
        'autores_relacionados' => ['Anna Freud', 'Wilfred Bion', 'Donald Winnicott'], 'obras_relacionadas' => [],
        'motores' => ['Nenhum (catalogação apenas)'], 'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Donald Winnicott', 'vida' => '1896–1971', 'nacionalidade' => 'Britânico', 'area' => 'Psicanálise',
        'vinculo' => 'Pediatra e psicanalista britânico da chamada Escola das Relações de Objeto (Independent Group), formado no ambiente pós-Klein da Sociedade Britânica de Psicanálise.',
        'conceitos' => ['Objeto transicional', 'Espaço potencial', 'Falso self', 'Holding'],
        'autores_relacionados' => ['Melanie Klein'], 'obras_relacionadas' => [],
        'motores' => ['Nenhum (catalogação apenas)'], 'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Wilfred Bion', 'vida' => '1897–1979', 'nacionalidade' => 'Britânico', 'area' => 'Psicanálise',
        'vinculo' => 'Analisado por Melanie Klein; desenvolveu a partir dela uma teoria própria do pensamento e da função de continência psíquica, com forte influência sobre a psicanálise de grupo e de psicoses.',
        'conceitos' => ['Função alfa', 'Continência (rêverie)', 'Elementos beta', 'Capacidade negativa'],
        'autores_relacionados' => ['Melanie Klein'], 'obras_relacionadas' => [],
        'motores' => ['Nenhum (catalogação apenas)'], 'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Sándor Ferenczi', 'vida' => '1873–1933', 'nacionalidade' => 'Húngaro', 'area' => 'Psicanálise',
        'vinculo' => 'Discípulo e amigo pessoal próximo de Freud desde os primeiros anos do movimento psicanalítico; divergências sobre técnica (técnica ativa) e sobre a realidade do trauma marcaram os últimos anos da relação entre os dois.',
        'conceitos' => ['Confusão de línguas entre adultos e crianças', 'Trauma', 'Técnica ativa'],
        'autores_relacionados' => ['Sigmund Freud', 'Otto Rank'], 'obras_relacionadas' => [],
        'motores' => ['Nenhum (catalogação apenas)'], 'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Karl Abraham', 'vida' => '1877–1925', 'nacionalidade' => 'Alemão', 'area' => 'Psicanálise',
        'vinculo' => 'Discípulo próximo de Freud e um dos primeiros analistas de Melanie Klein; sua teoria dos estágios pré-genitais da libido antecede e prepara conceitos retomados por Klein.',
        'conceitos' => ['Fases pré-genitais da libido', 'Melancolia', 'Erotismo oral'],
        'autores_relacionados' => ['Sigmund Freud', 'Melanie Klein'], 'obras_relacionadas' => ['Luto e Melancolia'],
        'motores' => ['Nenhum (catalogação apenas)'], 'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Otto Rank', 'vida' => '1884–1939', 'nacionalidade' => 'Austríaco', 'area' => 'Psicanálise',
        'vinculo' => 'Discípulo muito próximo de Freud por quase duas décadas (chegou a ser secretário da Sociedade Psicanalítica de Viena); rompimento teórico na década de 1920 em torno da teoria do trauma de nascimento.',
        'conceitos' => ['Trauma do nascimento', 'Vontade'],
        'autores_relacionados' => ['Sigmund Freud', 'Sándor Ferenczi'], 'obras_relacionadas' => [],
        'motores' => ['Nenhum (catalogação apenas)'], 'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Anna Freud', 'vida' => '1895–1982', 'nacionalidade' => 'Austro-britânica', 'area' => 'Psicanálise',
        'vinculo' => 'Filha mais nova de Sigmund Freud e sua herdeira teórica mais direta; desenvolveu a psicologia do ego e a técnica de análise infantil, em disputa institucional com Melanie Klein na Sociedade Britânica de Psicanálise.',
        'conceitos' => ['Mecanismos de defesa do ego', 'Psicologia do ego', 'Análise infantil'],
        'autores_relacionados' => ['Sigmund Freud', 'Melanie Klein'], 'obras_relacionadas' => [],
        'motores' => ['Nenhum (catalogação apenas)'], 'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Françoise Dolto', 'vida' => '1908–1988', 'nacionalidade' => 'Francesa', 'area' => 'Psicanálise',
        'vinculo' => 'Pioneira da psicanálise de crianças na França; destinatária da carta "Nota sobre a Criança" de Lacan, participante ativa da École Freudienne de Paris.',
        'conceitos' => ['Imagem inconsciente do corpo', 'Análise de crianças'],
        'autores_relacionados' => ['Jacques Lacan'], 'obras_relacionadas' => ['Nota sobre a Criança'],
        'motores' => ['Nenhum (catalogação apenas)'], 'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Jean Laplanche', 'vida' => '1924–2012', 'nacionalidade' => 'Francês', 'area' => 'Psicanálise',
        'vinculo' => 'Foi analisando de Jacques Lacan e, posteriormente, um de seus críticos teóricos mais rigorosos; coautor, com Jean-Bertrand Pontalis, do Vocabulário da Psicanálise (1967), obra de referência lexicográfica do campo.',
        'conceitos' => ['Sedução generalizada', 'Mensagem enigmática'],
        'autores_relacionados' => ['Jacques Lacan', 'Jean-Bertrand Pontalis'], 'obras_relacionadas' => [],
        'motores' => ['Nenhum (catalogação apenas)'], 'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Jean-Bertrand Pontalis', 'vida' => '1924–2013', 'nacionalidade' => 'Francês', 'area' => 'Psicanálise',
        'vinculo' => 'Foi analisando de Jacques Lacan; coautor, com Jean Laplanche, do Vocabulário da Psicanálise (1967) e coautor do conceito de "fantasia originária".',
        'conceitos' => ['Vocabulário psicanalítico', 'Fantasia originária'],
        'autores_relacionados' => ['Jacques Lacan', 'Jean Laplanche'], 'obras_relacionadas' => [],
        'motores' => ['Nenhum (catalogação apenas)'], 'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Jacques-Alain Miller', 'vida' => 'n. 1944', 'nacionalidade' => 'Francês', 'area' => 'Psicanálise',
        'vinculo' => 'Genro de Jacques Lacan e editor responsável pelo estabelecimento e publicação da quase totalidade dos volumes de O Seminário a partir das gravações/transcrições das aulas; fundador da Escola da Causa Freudiana e da Associação Mundial de Psicanálise (AMP).',
        'conceitos' => ['Estabelecimento do Seminário', 'Orientação lacaniana'],
        'autores_relacionados' => ['Jacques Lacan'], 'obras_relacionadas' => [],
        'motores' => ['Nenhum (catalogação apenas)'], 'status' => 'Catalogado', 'observacoes' => 'Toda a datação de publicação dos volumes de O Seminário catalogados em Lacan/Seminarios/ que citam edição estabelecida por Jacques-Alain Miller depende do trabalho editorial deste autor.'],
    ['nome' => 'Serge Leclaire', 'vida' => '1924–1994', 'nacionalidade' => 'Francês', 'area' => 'Psicanálise',
        'vinculo' => 'Um dos primeiros e mais próximos discípulos diretos de Jacques Lacan, participante da fundação da École Freudienne de Paris.',
        'conceitos' => ['Letra', 'Significante unário'],
        'autores_relacionados' => ['Jacques Lacan'], 'obras_relacionadas' => [],
        'motores' => ['Nenhum (catalogação apenas)'], 'status' => 'Catalogado', 'observacoes' => ''],
    ['nome' => 'Antonio Quinet', 'vida' => 'n. 1953', 'nacionalidade' => 'Brasileiro', 'area' => 'Psicanálise',
        'vinculo' => 'Psicanalista lacaniano brasileiro contemporâneo, comentador sistemático da obra de Lacan (em especial psicose e a teoria dos discursos) e figura de referência da recepção lacaniana no Brasil.',
        'conceitos' => ['Psicose', 'O olhar', 'Teoria dos discursos'],
        'autores_relacionados' => ['Jacques Lacan'], 'obras_relacionadas' => [],
        'motores' => ['Nenhum (catalogação apenas)'], 'status' => 'Catalogado', 'observacoes' => 'Único autor desta lista contemporâneo e brasileiro — incluído por indicação explícita da Sprint, relevante para a recepção lacaniana no contexto de origem do próprio PsycheAI.'],
];
