<?php
declare(strict_types=1);

/**
 * Dataset — os 21 conceitos canônicos (10 de Ontologia-Freud.md §3 + 11 de
 * Ontologia-Lacan.md §3), únicos documentos da Biblioteca Teórica com as
 * seções "Aplicação Computacional" e "Representação Computacional"
 * (decisões de arquitetura desta Sprint, v1 e v2). Todo campo relativo a
 * componentes/telas reais é auditado contra o estado do código na data
 * desta Sprint (Roadmap.md até a Sprint 24) — nunca uma intenção futura
 * apresentada como fato. "Visão do Sujeito" nunca inclui vocabulário
 * técnico, rótulo estrutural ou classificação — apenas o comportamento
 * observável da IA e as perguntas que ele autoriza/proíbe, em linha com o
 * princípio de separação Sujeito/Analista (Documento-Mestre.md §5).
 */

$naoImplementadoSujeito = [
    'sujeito_pode_perceber' => 'Não — o conceito não tem manifestação computacional perceptível nesta versão; nenhuma tela ou mensagem o nomeia.',
    'perguntas_permitidas' => 'Nenhuma pergunta é derivada diretamente deste conceito nesta versão.',
];
$naoImplementadoAnalista = [
    'como_e_apresentado' => 'Não é apresentado como estrutura própria nesta versão — existe apenas como fundamentação teórica citada em texto (Ontologia correspondente e esta Biblioteca), nunca como tela, widget ou rótulo.',
    'visualizacoes_produzidas' => 'Nenhuma.',
    'relacoes_exibidas' => 'Nenhuma.',
    'evidencias_que_sustentam' => [],
    'motores_que_produzem' => [],
    'componentes_participantes' => [],
];

return [
    // ===================== FREUD (Ontologia-Freud.md §3) =====================
    [
        'autor' => 'Sigmund Freud', 'conceito' => 'Inconsciente', 'obra_origem' => 'O Inconsciente',
        'ano' => '1915', 'idioma' => 'Alemão', 'area' => 'Freud',
        'conceitos_relacionados' => ['Recalque', 'Pulsão', 'Formação de compromisso'],
        'autores_relacionados' => ['Jacques Lacan'], 'obras_relacionadas' => ['O Inconsciente', 'A Repressão (O Recalque)'],
        'status' => 'Catalogado',
        'observacoes' => 'Núcleo estrutural da ontologia (Ontologia-Freud.md §4), junto com Recalque.',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'Nenhum diretamente — o conceito serve exclusivamente como justificativa teórica para que o sistema trate recorrências e relações no discurso registrado como potencialmente relevantes, nunca como algo que o sistema observa ou infere.',
            'fundamentacao_cientifica' => 'O Inconsciente (Freud, 1915) — ver Ontologia-Freud.md §3.1.',
            'dados_necessarios' => [], 'dados_opcionais' => [], 'eventos_que_podem_origina_lo' => [],
            'relacoes_com_outros_conceitos' => 'Núcleo estrutural com Recalque (Ontologia-Freud.md §4); pressuposto teórico de toda Formação de compromisso e suas espécies.',
            'componentes' => [],
            'observado_automaticamente' => 'Não — limite explícito em Documento-Mestre.md §6.5 ("o sistema não opera sobre o inconsciente").',
            'organizado_automaticamente' => 'Não.', 'classificado_automaticamente' => 'Não.',
            'depende_confirmacao_sujeito' => 'Sim — qualquer leitura permanece de responsabilidade do sujeito ou do analista (Regra 10).',
            'depende_validacao_analista' => 'Sim.', 'evidencias_produzidas' => [],
            'limitacoes_computacionais' => 'Ontologia-Freud.md §5 não descreve como detectar, inferir ou operacionalizar o inconsciente a partir do discurso registrado — isso permanece, por definição, fora do alcance do sistema.',
            'trabalhos_relacionados' => ['O Inconsciente', 'A Repressão (O Recalque)'],
            'motores_impactados' => ['Nenhum (fundamentação teórica de fundo para Freud Engine e Lacan Engine)'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => [
                'interfere_na_conversa' => 'Não interfere diretamente — não há observação computacional deste conceito; ele apenas justifica, de forma indireta e distante, por que o sistema presta atenção a recorrências no discurso (ver Repetição).',
                'sujeito_pode_perceber' => 'Não — o conceito não tem manifestação computacional perceptível; nenhuma tela ou mensagem o nomeia.',
                'comportamento_da_ia' => 'A IA nunca afirma nem sugere ter acesso ao inconsciente do Sujeito, em nenhuma camada — limite absoluto de Documento-Mestre.md §6.5.',
                'perguntas_permitidas' => 'Nenhuma pergunta é derivada diretamente deste conceito — perguntas socráticas reais partem de Repetição, nunca de Inconsciente enquanto tal.',
                'perguntas_proibidas' => 'Qualquer pergunta ou afirmação que pressuponha acesso do sistema ao inconsciente do Sujeito (ex.: "o que seu inconsciente está tentando dizer").',
            ],
            'visao_analista' => $naoImplementadoAnalista,
        ],
    ],
    [
        'autor' => 'Sigmund Freud', 'conceito' => 'Recalque', 'obra_origem' => 'A Repressão (O Recalque)',
        'ano' => '1915', 'idioma' => 'Alemão', 'area' => 'Freud',
        'conceitos_relacionados' => ['Inconsciente', 'Formação de compromisso', 'Ato falho'],
        'autores_relacionados' => ['Jacques Lacan'], 'obras_relacionadas' => ['A Repressão (O Recalque)', 'O Inconsciente'],
        'status' => 'Catalogado', 'observacoes' => '',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'Justifica teoricamente por que descontinuidades, lacunas, substituições e correções no EventoDiscursivo registrado são categorias dignas de preservação — nunca inferir o que estaria sendo recalcado.',
            'fundamentacao_cientifica' => 'A Repressão / O Recalque (Freud, 1915) — ver Ontologia-Freud.md §3.2.',
            'dados_necessarios' => ['EventoDiscursivo.conteudo (preservado tal como produzido, sem correção editorial)'],
            'dados_opcionais' => [], 'eventos_que_podem_origina_lo' => ['Registro de um EventoDiscursivo com lacuna, substituição ou autocorreção aparente — apenas preservado, nunca classificado como recalque'],
            'relacoes_com_outros_conceitos' => 'Núcleo estrutural com Inconsciente; base para Formação de compromisso, Ato falho, Chiste e Sonhos (Ontologia-Freud.md §4).',
            'componentes' => ['Nenhum classifica conteúdo como "recalcado" — RegistrarEventoDiscursivoHandler preserva o conteúdo tal como produzido, compatível com o conceito mas não decorrente dele'],
            'observado_automaticamente' => 'Não.', 'organizado_automaticamente' => 'Não.', 'classificado_automaticamente' => 'Não.',
            'depende_confirmacao_sujeito' => 'Sim.', 'depende_validacao_analista' => 'Sim.', 'evidencias_produzidas' => [],
            'limitacoes_computacionais' => 'Ontologia-Freud.md §5 — não descreve como detectar ou inferir o recalque computacionalmente.',
            'trabalhos_relacionados' => ['A Repressão (O Recalque)', 'O Inconsciente'],
            'motores_impactados' => ['Nenhum (fundamentação teórica de fundo)'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => [
                'interfere_na_conversa' => 'Não interfere diretamente — justifica apenas que o EventoDiscursivo preserve o conteúdo tal como produzido, sem correção.',
                'sujeito_pode_perceber' => 'Não.',
                'comportamento_da_ia' => 'A IA nunca corrige, completa ou "destrava" o que o Sujeito não conseguiu dizer — preserva a lacuna tal como ela aparece no registro.',
                'perguntas_permitidas' => 'Nenhuma pergunta é derivada diretamente deste conceito nesta versão.',
                'perguntas_proibidas' => 'Qualquer pergunta que nomeie "recalque" ou pressuponha saber o que está sendo recalcado.',
            ],
            'visao_analista' => $naoImplementadoAnalista,
        ],
    ],
    [
        'autor' => 'Sigmund Freud', 'conceito' => 'Pulsão', 'obra_origem' => 'Pulsões e seus Destinos',
        'ano' => '1915', 'idioma' => 'Alemão', 'area' => 'Freud',
        'conceitos_relacionados' => ['Desejo', 'Repetição', 'Formação de compromisso'],
        'autores_relacionados' => [], 'obras_relacionadas' => ['Pulsões e seus Destinos', 'Três Ensaios sobre a Teoria da Sexualidade'],
        'status' => 'Catalogado', 'observacoes' => '',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'Sustenta teoricamente a hipótese de que elementos discursivos podem se apresentar com insistência — retornando, deslocando-se, buscando novas vias — base teórica do eixo de recorrência já implementado.',
            'fundamentacao_cientifica' => 'Pulsões e seus Destinos (Freud, 1915); Três Ensaios sobre a Teoria da Sexualidade (1905) — ver Ontologia-Freud.md §3.3.',
            'dados_necessarios' => ['EventoDiscursivo.conteudo normalizado através de múltiplas Sessões, para observar insistência ao longo do tempo'],
            'dados_opcionais' => ['OcorrenciaRecorrencia (circuito) — mostra o trajeto, não a pulsão em si'],
            'eventos_que_podem_origina_lo' => ['Registro de múltiplos EventoDiscursivo com conteúdo normalizado equivalente ao longo de Sessões distintas'],
            'relacoes_com_outros_conceitos' => 'Força motriz junto com Desejo (Ontologia-Freud.md §4); base teórica da Repetição.',
            'componentes' => ['Domain/Services/DetectorRecorrencias — observa insistência de conteúdo, mas nomeia isso "recorrência", nunca "pulsão"'],
            'observado_automaticamente' => 'Não — o que é observado é recorrência de conteúdo (um efeito possível), nunca a pulsão como tal.',
            'organizado_automaticamente' => 'Não.', 'classificado_automaticamente' => 'Não.',
            'depende_confirmacao_sujeito' => 'Sim.', 'depende_validacao_analista' => 'Sim.',
            'evidencias_produzidas' => ['Recorrencia (contagem de ocorrências de conteúdo normalizado) — nunca rotulada como "pulsão" na saída do sistema'],
            'limitacoes_computacionais' => 'Ontologia-Freud.md §5 — a pulsão, como conceito-limite entre o somático e o psíquico, não tem correlato observável direto em texto.',
            'trabalhos_relacionados' => ['Pulsões e seus Destinos', 'Três Ensaios sobre a Teoria da Sexualidade'],
            'motores_impactados' => ['Freud Engine (fundamentação teórica de fundo para DetectorRecorrencias, sem nomear o conceito na saída)'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => [
                'interfere_na_conversa' => 'Não interfere diretamente — fundamenta, de fundo, por que insistência de conteúdo (Repetição) é tratada como relevante pelo Freud Engine.',
                'sujeito_pode_perceber' => 'Não — o Sujeito nunca vê o termo "pulsão" nem qualquer rótulo derivado dele.',
                'comportamento_da_ia' => 'A IA não nomeia pulsão em nenhuma resposta ao Sujeito; no máximo reflete a insistência de um tema via pergunta-eco (RespostaEcoRecorrenciaService), já registrada sob o conceito de Repetição.',
                'perguntas_permitidas' => 'Nenhuma pergunta é derivada diretamente deste conceito — a pergunta-eco pertence ao conceito de Repetição.',
                'perguntas_proibidas' => 'Qualquer pergunta que nomeie pulsão, fonte, pressão, finalidade ou objeto pulsional.',
            ],
            'visao_analista' => array_merge($naoImplementadoAnalista, [
                'como_e_apresentado' => 'Não é apresentado como estrutura própria; a insistência que ele fundamenta aparece ao analista apenas como Recorrencia/circuito, rotulados nesses termos, nunca como "pulsão".',
            ]),
        ],
    ],
    [
        'autor' => 'Sigmund Freud', 'conceito' => 'Desejo (Freud)', 'obra_origem' => 'A Interpretação dos Sonhos',
        'ano' => '1900', 'idioma' => 'Alemão', 'area' => 'Freud',
        'conceitos_relacionados' => ['Pulsão', 'Sonhos', 'Repetição'],
        'autores_relacionados' => [], 'obras_relacionadas' => ['A Interpretação dos Sonhos'],
        'status' => 'Catalogado',
        'observacoes' => 'Distinto do Desejo lacaniano (Conceitos/desejo-lacaniano.md) — nota de escopo em Ontologia-Freud.md §3.4, não fundidos nesta Biblioteca.',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'Fundamenta por que associações e repetições ao longo do tempo — não apenas o conteúdo isolado — podem ser candidatas a estrutura discursiva relevante, reforçando a importância da temporalidade.',
            'fundamentacao_cientifica' => 'A Interpretação dos Sonhos (Freud, 1900) — ver Ontologia-Freud.md §3.4.',
            'dados_necessarios' => ['EventoDiscursivo.criadoEm', 'Sessao.data (temporalidade)'],
            'dados_opcionais' => ['Relato de sonho registrado como EventoDiscursivo, sem classificação automática de "desejo realizado"'],
            'eventos_que_podem_origina_lo' => [],
            'relacoes_com_outros_conceitos' => 'Força motriz junto com Pulsão (Ontologia-Freud.md §4); distinto do Desejo lacaniano.',
            'componentes' => ['Nenhum nomeia "desejo" diretamente — a temporalidade que ele fundamenta é usada por LinhaDoTempoApplicationService e por DetectorRecorrencias::detectarCircuito()'],
            'observado_automaticamente' => 'Não.', 'organizado_automaticamente' => 'Não (a organização cronológica em si é função técnica de LinhaDoTempoApplicationService, não "organização do desejo").', 'classificado_automaticamente' => 'Não.',
            'depende_confirmacao_sujeito' => 'Sim.', 'depende_validacao_analista' => 'Sim.', 'evidencias_produzidas' => [],
            'limitacoes_computacionais' => 'Ontologia-Freud.md §5; ver também nota de escopo distinguindo do Desejo lacaniano.',
            'trabalhos_relacionados' => ['A Interpretação dos Sonhos'],
            'motores_impactados' => ['Nenhum (fundamentação teórica de fundo para a temporalidade usada pelo Freud Engine)'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => [
                'interfere_na_conversa' => 'Não interfere diretamente — fundamenta a importância da temporalidade usada pela Linha do Tempo e pelo circuito de recorrências.',
                'sujeito_pode_perceber' => 'Não.',
                'comportamento_da_ia' => 'A IA nunca nomeia "desejo" na conversa; no máximo dá continuidade à fala do Sujeito via Motor de Enunciação Socrática, sem atribuir causa ou objeto de desejo.',
                'perguntas_permitidas' => 'Perguntas de continuidade genéricas do Motor de Enunciação Socrática (GeradorDePerguntaSocraticaLLM), que dão sequência ao assunto trazido pelo Sujeito sem nomear desejo.',
                'perguntas_proibidas' => 'Qualquer pergunta que afirme ou sugira o que o Sujeito "realmente deseja" ou "realmente quer dizer".',
            ],
            'visao_analista' => array_merge($naoImplementadoAnalista, [
                'como_e_apresentado' => 'Não é apresentado como estrutura própria; a Linha do Tempo (LinhaDoTempoApplicationService) e o circuito de recorrências são as únicas representações temporais disponíveis ao analista, sem nomear "desejo".',
                'componentes_participantes' => ['LinhaDoTempoApplicationService'],
            ]),
        ],
    ],
    [
        'autor' => 'Sigmund Freud', 'conceito' => 'Formação de compromisso', 'obra_origem' => 'Psicopatologia da Vida Cotidiana',
        'ano' => '1901', 'idioma' => 'Alemão', 'area' => 'Freud',
        'conceitos_relacionados' => ['Ato falho', 'Chiste', 'Sonhos'],
        'autores_relacionados' => [], 'obras_relacionadas' => ['Psicopatologia da Vida Cotidiana', 'A Interpretação dos Sonhos', 'Os Chistes e sua Relação com o Inconsciente'],
        'status' => 'Catalogado', 'observacoes' => 'Categoria geral da qual Ato falho, Chiste e Sonhos são espécies (Ontologia-Freud.md §4).',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'Fornece base teórica para que EventoDiscursivo associados a atos falhos, chistes e relatos de sonho recebam atenção estrutural particular — sem que o sistema afirme que são, de fato, formações de compromisso.',
            'fundamentacao_cientifica' => 'Psicopatologia da Vida Cotidiana (Freud, 1901) — ver Ontologia-Freud.md §3.5.',
            'dados_necessarios' => ['EventoDiscursivo.conteudo'],
            'dados_opcionais' => ['ContextoConversaDTO (turnos recentes da Sessao) — usado pelo Motor de Enunciação Socrática, não pela classificação em si'],
            'eventos_que_podem_origina_lo' => ['Mensagem enviada pelo Sujeito, classificada pelo Motor Freud (LLM)'],
            'relacoes_com_outros_conceitos' => 'Categoria geral da qual Ato falho, Chiste e Sonhos são espécies (Ontologia-Freud.md §4).',
            'componentes' => ['Domain enum TipoFormacaoFreudiana (valor FormacaoDeCompromisso, um dos 6 do enum fechado)', 'Infrastructure/AI/ClassificadorFreudianoLLM', 'Application/UseCases/ClassificarFormacaoFreudiana'],
            'observado_automaticamente' => 'Sim — via classificação estrutural por LLM com guardrail de enum fechado (Revisão do Motor Freud, Roadmap.md).',
            'organizado_automaticamente' => 'Não — a classificação rotula um EventoDiscursivo isolado, não organiza um conjunto.',
            'classificado_automaticamente' => 'Sim — TipoFormacaoFreudiana::FormacaoDeCompromisso é um dos 6 valores possíveis (os demais: AtoFalho, Chiste, Sonho, Repeticao, NaoClassificado).',
            'depende_confirmacao_sujeito' => 'Não diretamente — o Sujeito nunca vê o rótulo (Regra 11, Regras-Dominio.md).',
            'depende_validacao_analista' => 'Sim — só as telas do analista exibem o rótulo (revisão pós-Sprint 16, Peça A).',
            'evidencias_produzidas' => ['TipoFormacaoFreudiana::FormacaoDeCompromisso (ou NaoClassificado quando o guardrail rejeita a resposta do LLM)'],
            'limitacoes_computacionais' => 'Reconhecer a forma de uma formação de compromisso não é interpretá-la — o sistema nunca atribui causa ou conteúdo recalcado (Regra 7).',
            'trabalhos_relacionados' => ['Psicopatologia da Vida Cotidiana', 'A Interpretação dos Sonhos', 'Os Chistes e sua Relação com o Inconsciente'],
            'motores_impactados' => ['Freud Engine'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => [
                'interfere_na_conversa' => 'Não interfere na resposta dada ao Sujeito — a classificação (TipoFormacaoFreudiana) roda em paralelo à conversa, mas nunca é usada para compor a resposta socrática (Regra 11).',
                'sujeito_pode_perceber' => 'Não — o rótulo nunca aparece em nenhuma tela ou resposta acessível ao Sujeito.',
                'comportamento_da_ia' => 'A IA responde ao Sujeito via Modo Socrático normalmente, sem sinalizar que uma classificação estrutural ocorreu em paralelo.',
                'perguntas_permitidas' => 'As perguntas socráticas genéricas já em produção (GeradorDePerguntaSocraticaLLM) — nunca fazem referência à classificação freudiana.',
                'perguntas_proibidas' => 'Qualquer pergunta que nomeie "formação de compromisso" ou pressuponha que o sistema identificou uma.',
            ],
            'visao_analista' => [
                'como_e_apresentado' => 'Apresentado na tela de Observações do Sujeito (rota `/sujeitos/{id}/observacoes`) como rótulo estrutural ao lado do Evento Discursivo classificado.',
                'visualizacoes_produzidas' => 'Rótulo de tipo de formação na tela de Observações (observacoes/mostrar.php).',
                'relacoes_exibidas' => 'Rótulo lacaniano correspondente, quando `comLeituraLacaniana=true` (ReclassificadorLacaniano::reclassificarPorTipoFreudiano()) e fundamentação teórica via fundamentacaoPara().',
                'evidencias_que_sustentam' => ['TipoFormacaoFreudiana::FormacaoDeCompromisso'],
                'motores_que_produzem' => ['Freud Engine'],
                'componentes_participantes' => ['ObservacoesSujeitoController', 'ClassificadorFreudianoLLM', 'ObservacaoApplicationService'],
            ],
        ],
    ],
    [
        'autor' => 'Sigmund Freud', 'conceito' => 'Ato falho', 'obra_origem' => 'Psicopatologia da Vida Cotidiana',
        'ano' => '1901', 'idioma' => 'Alemão', 'area' => 'Freud',
        'conceitos_relacionados' => ['Formação de compromisso', 'Recalque', 'Desejo (Freud)'],
        'autores_relacionados' => [], 'obras_relacionadas' => ['Psicopatologia da Vida Cotidiana'],
        'status' => 'Catalogado', 'observacoes' => '',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'Justifica que interrupções, autocorreções e desvios no discurso registrado sejam preservados como classe própria de EventoDiscursivo — sem inferir a intenção inconsciente subjacente.',
            'fundamentacao_cientifica' => 'Psicopatologia da Vida Cotidiana (Freud, 1901) — ver Ontologia-Freud.md §3.6.',
            'dados_necessarios' => ['EventoDiscursivo.conteudo'], 'dados_opcionais' => [],
            'eventos_que_podem_origina_lo' => ['Mensagem do Sujeito classificada pelo Motor Freud'],
            'relacoes_com_outros_conceitos' => 'Espécie de Formação de compromisso; ligado ao Recalque (o que retorna) e ao Desejo (o que busca expressão) — Ontologia-Freud.md §4.',
            'componentes' => ['TipoFormacaoFreudiana::AtoFalho', 'Infrastructure/AI/ClassificadorFreudianoLLM'],
            'observado_automaticamente' => 'Sim.', 'organizado_automaticamente' => 'Não.', 'classificado_automaticamente' => 'Sim.',
            'depende_confirmacao_sujeito' => 'Não diretamente.', 'depende_validacao_analista' => 'Sim.',
            'evidencias_produzidas' => ['TipoFormacaoFreudiana::AtoFalho'],
            'limitacoes_computacionais' => 'Reconhecer a forma não é inferir a intenção inconsciente — permanece fora do alcance do sistema (Ontologia-Freud.md §5).',
            'trabalhos_relacionados' => ['Psicopatologia da Vida Cotidiana'],
            'motores_impactados' => ['Freud Engine'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => [
                'interfere_na_conversa' => 'Não interfere na resposta dada ao Sujeito — a classificação roda em paralelo, nunca compõe a resposta socrática (Regra 11).',
                'sujeito_pode_perceber' => 'Não.',
                'comportamento_da_ia' => 'A IA nunca sinaliza ao Sujeito que um ato falho foi reconhecido — responde normalmente via Modo Socrático.',
                'perguntas_permitidas' => 'As perguntas socráticas genéricas já em produção — nunca fazem referência à classificação.',
                'perguntas_proibidas' => 'Qualquer pergunta que nomeie "ato falho" ou pressuponha intenção inconsciente por trás de um lapso.',
            ],
            'visao_analista' => [
                'como_e_apresentado' => 'Apresentado na tela de Observações do Sujeito como rótulo estrutural ao lado do Evento Discursivo classificado.',
                'visualizacoes_produzidas' => 'Rótulo de tipo de formação na tela de Observações.',
                'relacoes_exibidas' => 'Rótulo lacaniano correspondente e fundamentação teórica, quando `comLeituraLacaniana=true`.',
                'evidencias_que_sustentam' => ['TipoFormacaoFreudiana::AtoFalho'],
                'motores_que_produzem' => ['Freud Engine'],
                'componentes_participantes' => ['ObservacoesSujeitoController', 'ClassificadorFreudianoLLM'],
            ],
        ],
    ],
    [
        'autor' => 'Sigmund Freud', 'conceito' => 'Chiste', 'obra_origem' => 'Os Chistes e sua Relação com o Inconsciente',
        'ano' => '1905', 'idioma' => 'Alemão', 'area' => 'Freud',
        'conceitos_relacionados' => ['Formação de compromisso', 'Sonhos', 'Metonímia'],
        'autores_relacionados' => ['Jacques Lacan'], 'obras_relacionadas' => ['Os Chistes e sua Relação com o Inconsciente', 'A Instância da Letra no Inconsciente ou a Razão desde Freud'],
        'status' => 'Catalogado', 'observacoes' => '',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'A exigência de um interlocutor reforça a importância do contexto de enunciação já previsto para EventoDiscursivo — o chiste é relacional, nunca isolado.',
            'fundamentacao_cientifica' => 'Os Chistes e sua Relação com o Inconsciente (Freud, 1905) — ver Ontologia-Freud.md §3.7; releitura estrutural em Ontologia-Lacan.md.',
            'dados_necessarios' => ['EventoDiscursivo.conteudo'], 'dados_opcionais' => ['Turnos anteriores da Sessao (contexto de enunciação)'],
            'eventos_que_podem_origina_lo' => ['Mensagem do Sujeito classificada pelo Motor Freud'],
            'relacoes_com_outros_conceitos' => 'Compartilha técnicas (condensação/deslocamento) com Sonhos; espécie de Formação de compromisso; releitura lacaniana em termos de Metáfora/Metonímia.',
            'componentes' => ['TipoFormacaoFreudiana::Chiste', 'Infrastructure/AI/ClassificadorFreudianoLLM', 'Domain/Services/ReclassificadorLacaniano::reclassificarPorTipoFreudiano() (tabela determinística que traduz o rótulo freudiano para vocabulário lacaniano)'],
            'observado_automaticamente' => 'Sim.', 'organizado_automaticamente' => 'Não.',
            'classificado_automaticamente' => 'Sim (Motor Freud, via LLM) e reclassificado em seguida (Motor Lacan, tabela determinística, sem LLM).',
            'depende_confirmacao_sujeito' => 'Não diretamente.', 'depende_validacao_analista' => 'Sim.',
            'evidencias_produzidas' => ['TipoFormacaoFreudiana::Chiste + rótulo lacaniano correspondente quando comLeituraLacaniana=true'],
            'limitacoes_computacionais' => 'O sistema reconhece a forma, nunca o efeito de prazer nem o conteúdo recalcado que o chiste expressaria.',
            'trabalhos_relacionados' => ['Os Chistes e sua Relação com o Inconsciente', 'A Instância da Letra no Inconsciente ou a Razão desde Freud'],
            'motores_impactados' => ['Freud Engine', 'Lacan Engine'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => [
                'interfere_na_conversa' => 'Não interfere na resposta dada ao Sujeito — a classificação roda em paralelo, nunca compõe a resposta socrática (Regra 11).',
                'sujeito_pode_perceber' => 'Não.',
                'comportamento_da_ia' => 'A IA pode acompanhar o tom leve de uma mensagem via Modo Socrático, mas nunca nomeia "chiste" nem indica reconhecimento da técnica.',
                'perguntas_permitidas' => 'As perguntas socráticas genéricas já em produção.',
                'perguntas_proibidas' => 'Qualquer pergunta que nomeie "chiste", "condensação" ou "deslocamento" para o Sujeito.',
            ],
            'visao_analista' => [
                'como_e_apresentado' => 'Apresentado na tela de Observações do Sujeito como rótulo estrutural ao lado do Evento Discursivo classificado.',
                'visualizacoes_produzidas' => 'Rótulo de tipo de formação e, lado a lado, a coluna "Leitura Lacaniana".',
                'relacoes_exibidas' => 'Rótulo lacaniano correspondente e fundamentação teórica (fundamentacaoPara()).',
                'evidencias_que_sustentam' => ['TipoFormacaoFreudiana::Chiste'],
                'motores_que_produzem' => ['Freud Engine', 'Lacan Engine'],
                'componentes_participantes' => ['ObservacoesSujeitoController', 'ClassificadorFreudianoLLM', 'ReclassificadorLacaniano'],
            ],
        ],
    ],
    [
        'autor' => 'Sigmund Freud', 'conceito' => 'Sonhos', 'obra_origem' => 'A Interpretação dos Sonhos',
        'ano' => '1900', 'idioma' => 'Alemão', 'area' => 'Freud',
        'conceitos_relacionados' => ['Formação de compromisso', 'Desejo (Freud)', 'Chiste'],
        'autores_relacionados' => [], 'obras_relacionadas' => ['A Interpretação dos Sonhos', 'Sobre os Sonhos', 'Complemento Metapsicológico à Teoria dos Sonhos'],
        'status' => 'Catalogado', 'observacoes' => '',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'As operações do trabalho do sonho (condensação/deslocamento) são o precedente teórico mais direto para tratar recorrência e deslocamento no discurso registrado como estruturalmente relevantes — sem interpretar o sonho relatado.',
            'fundamentacao_cientifica' => 'A Interpretação dos Sonhos (Freud, 1900) — ver Ontologia-Freud.md §3.8.',
            'dados_necessarios' => ['EventoDiscursivo.conteudo (relato do sonho, tratado como qualquer outro material discursivo)'], 'dados_opcionais' => [],
            'eventos_que_podem_origina_lo' => ['Mensagem do Sujeito classificada pelo Motor Freud'],
            'relacoes_com_outros_conceitos' => 'Modelo para o Chiste e para toda Formação de compromisso; ligado ao Desejo (realização de desejo) e ao Recalque (razão da distorção).',
            'componentes' => ['TipoFormacaoFreudiana::Sonho', 'Infrastructure/AI/ClassificadorFreudianoLLM'],
            'observado_automaticamente' => 'Sim (reconhecimento de forma, não interpretação de conteúdo onírico).', 'organizado_automaticamente' => 'Não.', 'classificado_automaticamente' => 'Sim.',
            'depende_confirmacao_sujeito' => 'Não diretamente.', 'depende_validacao_analista' => 'Sim.',
            'evidencias_produzidas' => ['TipoFormacaoFreudiana::Sonho'],
            'limitacoes_computacionais' => 'O sistema nunca interpreta o sonho relatado — apenas registra o relato como material discursivo (Ontologia-Freud.md §3.8).',
            'trabalhos_relacionados' => ['A Interpretação dos Sonhos', 'Sobre os Sonhos', 'Complemento Metapsicológico à Teoria dos Sonhos'],
            'motores_impactados' => ['Freud Engine'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => [
                'interfere_na_conversa' => 'Não interfere na resposta dada ao Sujeito — a classificação roda em paralelo, nunca compõe a resposta socrática (Regra 11).',
                'sujeito_pode_perceber' => 'Não.',
                'comportamento_da_ia' => 'Quando o Sujeito relata um sonho, a IA responde via Modo Socrático como a qualquer outro conteúdo — sem sinalizar reconhecimento de "relato onírico".',
                'perguntas_permitidas' => 'Perguntas de continuidade socráticas genéricas, que podem convidar o Sujeito a seguir falando sobre o que relatou.',
                'perguntas_proibidas' => 'Qualquer pergunta que ofereça interpretação do sonho ou nomeie "trabalho do sonho", "condensação" ou "deslocamento".',
            ],
            'visao_analista' => [
                'como_e_apresentado' => 'Apresentado na tela de Observações do Sujeito como rótulo estrutural ao lado do Evento Discursivo classificado.',
                'visualizacoes_produzidas' => 'Rótulo de tipo de formação na tela de Observações.',
                'relacoes_exibidas' => 'Rótulo lacaniano correspondente e fundamentação teórica, quando aplicável.',
                'evidencias_que_sustentam' => ['TipoFormacaoFreudiana::Sonho'],
                'motores_que_produzem' => ['Freud Engine'],
                'componentes_participantes' => ['ObservacoesSujeitoController', 'ClassificadorFreudianoLLM'],
            ],
        ],
    ],
    [
        'autor' => 'Sigmund Freud', 'conceito' => 'Repetição', 'obra_origem' => 'Além do Princípio do Prazer',
        'ano' => '1920', 'idioma' => 'Alemão', 'area' => 'Freud',
        'conceitos_relacionados' => ['Transferência', 'Pulsão', 'Metonímia'],
        'autores_relacionados' => ['Jacques Lacan'], 'obras_relacionadas' => ['Além do Princípio do Prazer', 'A Dinâmica da Transferência', 'Recordar, Repetir e Elaborar'],
        'status' => 'Catalogado', 'observacoes' => 'Conceito com o maior grau de implementação computacional real de toda a Biblioteca Teórica nesta versão.',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'É o conceito mais diretamente implementado do sistema — fundamenta diretamente a detecção de recorrência de conteúdo ao longo do tempo como objeto teórico relevante (atenção flutuante, Documento-Mestre.md §6.7).',
            'fundamentacao_cientifica' => 'Além do Princípio do Prazer (Freud, 1920) — ver Ontologia-Freud.md §3.9.',
            'dados_necessarios' => ['EventoDiscursivo.conteudo (normalizado — trim + minúsculas, desde a Sprint 15)', 'Sessao.data / EventoDiscursivo.criadoEm (para o circuito/trajeto)'],
            'dados_opcionais' => [], 'eventos_que_podem_origina_lo' => ['Dois ou mais EventoDiscursivo com o mesmo conteúdo normalizado, em qualquer Sessao do mesmo Sujeito'],
            'relacoes_com_outros_conceitos' => 'Intersecta a Transferência (repetição encenada na relação em vez de lembrada) e a Pulsão (um de seus destinos possíveis) — Ontologia-Freud.md §4.',
            'componentes' => ['Domain/Services/DetectorRecorrencias (detectar(), normalizar(), detectarCircuito())', 'Domain/Entities/Recorrencia', 'Domain/Specifications/RecorrenciaMinimaSpecification (limiar mínimo=2)', 'Domain/ValueObjects/OcorrenciaRecorrencia', 'Application/Services/ObservacaoApplicationService'],
            'observado_automaticamente' => 'Sim.',
            'organizado_automaticamente' => 'Sim — GeradorObservacoes/CicloDeObservacaoService organizam recorrências em Observacao; o circuito organiza a ordem cronológica das ocorrências entre Sessões.',
            'classificado_automaticamente' => 'Não — a recorrência é contada e organizada, nunca classificada quanto a causa ou sentido.',
            'depende_confirmacao_sujeito' => 'Não diretamente na tela do Sujeito (Regra 11: /conversa* nunca expõe isso); RespostaEcoRecorrenciaService devolve pergunta-eco ao Sujeito, nunca afirmação.',
            'depende_validacao_analista' => 'Sim — toda leitura de causa da repetição é do analista (Regra 10).',
            'evidencias_produzidas' => ['Recorrencia (conteúdo normalizado + contagem)', 'Observacao', 'CircuitoRecorrenciaDTO (trajeto cronológico entre Sessões)'],
            'limitacoes_computacionais' => 'O sistema nunca afirma por que algo se repete — apenas que se repete (Regra 7, Regras-Dominio.md).',
            'trabalhos_relacionados' => ['Além do Princípio do Prazer', 'A Dinâmica da Transferência', 'Recordar, Repetir e Elaborar'],
            'motores_impactados' => ['Discourse Engine', 'Freud Engine', 'Lacan Engine', 'Modo Socrático'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => [
                'interfere_na_conversa' => 'Sim, indiretamente — quando uma recorrência é detectada, RespostaEcoRecorrenciaService/RespostaSocraticaService devolvem uma pergunta-eco ao Sujeito nomeando a repetição, sem interpretar a causa.',
                'sujeito_pode_perceber' => 'Sim, de forma limitada — o Sujeito pode notar que o sistema "percebeu" que voltou a falar em algo, mas nunca vê a palavra "recorrência", contagem ou circuito.',
                'comportamento_da_ia' => 'Devolve pergunta-eco ("Você voltou a falar em \'%s\'. O que vem à mente sobre isso?") — nunca afirma que há repetição como fato objetivo, apenas pergunta a partir dela.',
                'perguntas_permitidas' => 'A pergunta-eco de RespostaEcoRecorrenciaService/RespostaSocraticaService, já em produção desde a Sprint 17.',
                'perguntas_proibidas' => 'Qualquer pergunta que cite contagem, data das ocorrências anteriores, ou nomeie "recorrência"/"circuito" para o Sujeito.',
            ],
            'visao_analista' => [
                'como_e_apresentado' => 'Apresentado nas telas de Observações (lista de recorrências e frequência) e no grafo do circuito (D3), rota `/sujeitos/{id}/observacoes/grafo-circuito`.',
                'visualizacoes_produzidas' => 'Tabela de recorrências com frequência; grafo de circuito (nós = Sessões em ordem cronológica, arestas = ocorrências consecutivas), via GrafoCircuitoViewModel.',
                'relacoes_exibidas' => 'Trajeto cronológico entre Sessões (CircuitoTrajetoComponent); rótulo lacaniano lado a lado, quando `comLeituraLacaniana=true`.',
                'evidencias_que_sustentam' => ['Recorrencia', 'Observacao', 'CircuitoRecorrenciaDTO'],
                'motores_que_produzem' => ['Discourse Engine', 'Freud Engine', 'Lacan Engine'],
                'componentes_participantes' => ['ObservacoesSujeitoController', 'GrafoCircuitoViewModel', 'CircuitoTrajetoComponent', 'RespostaEcoRecorrenciaService (produz a peça do lado do Sujeito)'],
            ],
        ],
    ],
    [
        'autor' => 'Sigmund Freud', 'conceito' => 'Transferência', 'obra_origem' => 'A Dinâmica da Transferência',
        'ano' => '1912', 'idioma' => 'Alemão', 'area' => 'Freud',
        'conceitos_relacionados' => ['Repetição', 'Outro', 'Desejo (Freud)'],
        'autores_relacionados' => [], 'obras_relacionadas' => ['A Dinâmica da Transferência', 'Recordar, Repetir e Elaborar'],
        'status' => 'Catalogado', 'observacoes' => '',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'Lembra que todo EventoDiscursivo ocorre dentro de uma relação situada, reforçando o "contexto de enunciação" e reafirmando que qualquer hipótese só tem sentido dentro da relação analítica real, nunca de forma autônoma.',
            'fundamentacao_cientifica' => 'A Dinâmica da Transferência (Freud, 1912); Recordar, Repetir e Elaborar (1914) — ver Ontologia-Freud.md §3.10.',
            'dados_necessarios' => ['Sessao (agrupa Discurso/EventoDiscursivo dentro de uma relação situada)'],
            'dados_opcionais' => ['ContextoConversaDTO (turnos recentes) — usado pelo Motor de Enunciação Socrática para dar continuidade à conversa, não para modelar transferência'],
            'eventos_que_podem_origina_lo' => [],
            'relacoes_com_outros_conceitos' => 'Forma de Repetição encenada na relação analítica; dirigida ao Outro (Ontologia-Freud.md §4; articulação com Ontologia-Lacan.md).',
            'componentes' => ['Nenhum nomeia "transferência" diretamente — a noção de relação situada que ela fundamenta já justifica Sessao como unidade de agrupamento'],
            'observado_automaticamente' => 'Não.', 'organizado_automaticamente' => 'Não.', 'classificado_automaticamente' => 'Não.',
            'depende_confirmacao_sujeito' => 'Sim.', 'depende_validacao_analista' => 'Sim.', 'evidencias_produzidas' => [],
            'limitacoes_computacionais' => 'Ontologia-Freud.md §5 — a transferência, por definição, só existe na relação analítica real, nunca de forma autônoma no sistema.',
            'trabalhos_relacionados' => ['A Dinâmica da Transferência', 'Recordar, Repetir e Elaborar'],
            'motores_impactados' => ['Nenhum (fundamentação teórica de fundo)'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => [
                'interfere_na_conversa' => 'Não interfere diretamente como estrutura nomeada — mas fundamenta por que a conversa é tratada como uma relação contínua (turnos recentes da Sessao), não como mensagens isoladas.',
                'sujeito_pode_perceber' => 'Não — o Sujeito percebe apenas a continuidade natural da conversa, nunca o conceito.',
                'comportamento_da_ia' => 'Usa os turnos recentes da Sessao (ContextoConversaDTO) para dar continuidade real ao assunto — sem nomear ou modelar "transferência".',
                'perguntas_permitidas' => 'Perguntas de continuidade do Motor de Enunciação Socrática, que já usam o histórico recente da Sessao.',
                'perguntas_proibidas' => 'Qualquer pergunta que nomeie "transferência" ou interprete o vínculo do Sujeito com o sistema/analista.',
            ],
            'visao_analista' => $naoImplementadoAnalista,
        ],
    ],

    // ===================== LACAN (Ontologia-Lacan.md §3) =====================
    [
        'autor' => 'Jacques Lacan', 'conceito' => 'Significante', 'obra_origem' => 'A Instância da Letra no Inconsciente ou a Razão desde Freud',
        'ano' => '1957', 'idioma' => 'Francês', 'area' => 'Lacan',
        'conceitos_relacionados' => ['Cadeia significante', 'Metáfora', 'Metonímia'],
        'autores_relacionados' => ['Ferdinand de Saussure'], 'obras_relacionadas' => ['A Instância da Letra no Inconsciente ou a Razão desde Freud'],
        'status' => 'Catalogado', 'observacoes' => 'Ver Documento-Mestre.md §6.6 — questão de pesquisa central do projeto, ainda sem resposta.',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'Nenhum ainda — é a questão de pesquisa central em aberto do projeto: como representar computacionalmente um significante sem reduzi-lo a uma simples palavra.',
            'fundamentacao_cientifica' => 'A Instância da Letra no Inconsciente ou a Razão desde Freud (Lacan, 1957) — ver Ontologia-Lacan.md §3.1.',
            'dados_necessarios' => [], 'dados_opcionais' => [], 'eventos_que_podem_origina_lo' => [],
            'relacoes_com_outros_conceitos' => 'Base da Cadeia significante, da Metáfora e da Metonímia (Ontologia-Lacan.md §4).',
            'componentes' => [],
            'observado_automaticamente' => 'Não — questão de pesquisa explicitamente em aberto (Documento-Mestre.md §6.6).',
            'organizado_automaticamente' => 'Não.', 'classificado_automaticamente' => 'Não.',
            'depende_confirmacao_sujeito' => 'Sim — só o sujeito, no processo analítico, confirma o estatuto de um significante (Ontologia-Lacan.md §5).',
            'depende_validacao_analista' => 'Sim.', 'evidencias_produzidas' => [],
            'limitacoes_computacionais' => 'Documento-Mestre.md §6.6; Ontologia-Lacan.md §5 — o sistema nunca identifica significante automaticamente.',
            'trabalhos_relacionados' => ['A Instância da Letra no Inconsciente ou a Razão desde Freud'],
            'motores_impactados' => ['Nenhum (questão de pesquisa aberta)'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => array_merge($naoImplementadoSujeito, [
                'interfere_na_conversa' => 'Não interfere — nenhuma representação computacional existe.',
                'comportamento_da_ia' => 'Nenhum comportamento é derivado deste conceito.',
                'perguntas_proibidas' => 'Qualquer pergunta que pressuponha identificação de um significante do Sujeito.',
            ]),
            'visao_analista' => $naoImplementadoAnalista,
        ],
    ],
    [
        'autor' => 'Jacques Lacan', 'conceito' => 'Cadeia significante', 'obra_origem' => 'A Instância da Letra no Inconsciente ou a Razão desde Freud',
        'ano' => '1957', 'idioma' => 'Francês', 'area' => 'Lacan',
        'conceitos_relacionados' => ['Significante', 'Metáfora', 'Metonímia'],
        'autores_relacionados' => [], 'obras_relacionadas' => ['A Instância da Letra no Inconsciente ou a Razão desde Freud', 'O Seminário sobre "A Carta Roubada"'],
        'status' => 'Catalogado', 'observacoes' => '',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'Nenhum implementado — Roadmap.md "Sprints futuras" registra que a cadeia de significantes como matema formal (S1↔S2) exige sprint de ontologia computacional própria antes de qualquer nó/aresta.',
            'fundamentacao_cientifica' => 'A Instância da Letra no Inconsciente ou a Razão desde Freud; O Seminário sobre "A Carta Roubada" — ver Ontologia-Lacan.md §3.2.',
            'dados_necessarios' => [], 'dados_opcionais' => [], 'eventos_que_podem_origina_lo' => [],
            'relacoes_com_outros_conceitos' => 'Composta por Significantes; base para Metáfora e Metonímia (Ontologia-Lacan.md §4).',
            'componentes' => [],
            'observado_automaticamente' => 'Não.', 'organizado_automaticamente' => 'Não.', 'classificado_automaticamente' => 'Não.',
            'depende_confirmacao_sujeito' => 'Sim.', 'depende_validacao_analista' => 'Sim.', 'evidencias_produzidas' => [],
            'limitacoes_computacionais' => 'Roadmap.md "Sprints futuras" — nenhuma representação computacional definida (S1/S2 como grafo).',
            'trabalhos_relacionados' => ['A Instância da Letra no Inconsciente ou a Razão desde Freud', 'O Seminário sobre "A Carta Roubada"'],
            'motores_impactados' => ['Nenhum'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => array_merge($naoImplementadoSujeito, [
                'interfere_na_conversa' => 'Não interfere — nenhuma representação computacional existe.',
                'comportamento_da_ia' => 'Nenhum comportamento é derivado deste conceito.',
                'perguntas_proibidas' => 'Qualquer pergunta que pressuponha montar ou expor uma cadeia de significantes do Sujeito.',
            ]),
            'visao_analista' => $naoImplementadoAnalista,
        ],
    ],
    [
        'autor' => 'Jacques Lacan', 'conceito' => 'Metáfora', 'obra_origem' => 'A Instância da Letra no Inconsciente ou a Razão desde Freud',
        'ano' => '1957', 'idioma' => 'Francês', 'area' => 'Lacan',
        'conceitos_relacionados' => ['Metonímia', 'Formação de compromisso', 'Significante'],
        'autores_relacionados' => ['Roman Jakobson'], 'obras_relacionadas' => ['A Instância da Letra no Inconsciente ou a Razão desde Freud', 'As Formações do Inconsciente (Seminário V)'],
        'status' => 'Catalogado', 'observacoes' => '',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'Fundamenta a releitura estrutural da condensação freudiana como substituição de um significante por outro — mapeado na tabela de reclassificação, mas não efetivamente disparado pela implementação atual.',
            'fundamentacao_cientifica' => 'A Instância da Letra no Inconsciente ou a Razão desde Freud — ver Ontologia-Lacan.md §4 (tabela Condensação→Metáfora).',
            'dados_necessarios' => ['Dois conteúdos distintos em relação de substituição um pelo outro — dado que DetectorRecorrencias não captura (só reconhece repetição do mesmo conteúdo normalizado)'],
            'dados_opcionais' => [], 'eventos_que_podem_origina_lo' => ['Nenhum evento dispara este rótulo na implementação atual'],
            'relacoes_com_outros_conceitos' => 'Par com Metonímia; releitura estrutural de Condensação (Ontologia-Freud.md).',
            'componentes' => ['Domain/Services/ReclassificadorLacaniano — a tabela de lookup prevê o rótulo, mas nunca é retornada na prática (Roadmap.md, Sprint 16: o detector só reconhece repetição literal, nunca substituição entre dois significantes distintos)'],
            'observado_automaticamente' => 'Não — mapeado teoricamente, mas nunca efetivamente produzido pela implementação atual.',
            'organizado_automaticamente' => 'Não.', 'classificado_automaticamente' => 'Não, na prática atual (previsto na tabela, sem caminho de código que o produza).',
            'depende_confirmacao_sujeito' => 'Sim.', 'depende_validacao_analista' => 'Sim.', 'evidencias_produzidas' => [],
            'limitacoes_computacionais' => 'Exigiria detectar substituição entre dois conteúdos distintos, não apenas repetição do mesmo conteúdo — mudança de escopo do detector ainda não decidida com o usuário.',
            'trabalhos_relacionados' => ['A Instância da Letra no Inconsciente ou a Razão desde Freud', 'As Formações do Inconsciente (Seminário V)'],
            'motores_impactados' => ['Lacan Engine (mapeado na tabela de reclassificação, não efetivamente produzido nesta versão)'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => array_merge($naoImplementadoSujeito, [
                'interfere_na_conversa' => 'Não interfere — nunca é efetivamente produzido pela implementação atual.',
                'comportamento_da_ia' => 'Nenhum comportamento é derivado deste conceito nesta versão.',
                'perguntas_proibidas' => 'Qualquer pergunta que nomeie "metáfora" ou estrutura de substituição significante para o Sujeito.',
            ]),
            'visao_analista' => [
                'como_e_apresentado' => 'Não é apresentado nesta versão — o rótulo existe na tabela de ReclassificadorLacaniano, mas nenhuma tela chega a exibi-lo porque o detector atual nunca o produz.',
                'visualizacoes_produzidas' => 'Nenhuma nesta versão.',
                'relacoes_exibidas' => 'Nenhuma nesta versão.',
                'evidencias_que_sustentam' => [],
                'motores_que_produzem' => [],
                'componentes_participantes' => ['ReclassificadorLacaniano (tabela de lookup, caminho de código não alcançado)'],
            ],
        ],
    ],
    [
        'autor' => 'Jacques Lacan', 'conceito' => 'Metonímia', 'obra_origem' => 'A Instância da Letra no Inconsciente ou a Razão desde Freud',
        'ano' => '1957', 'idioma' => 'Francês', 'area' => 'Lacan',
        'conceitos_relacionados' => ['Metáfora', 'Repetição', 'Significante'],
        'autores_relacionados' => ['Roman Jakobson'], 'obras_relacionadas' => ['A Instância da Letra no Inconsciente ou a Razão desde Freud', 'O Seminário sobre "A Carta Roubada"'],
        'status' => 'Catalogado', 'observacoes' => 'Único conceito lacaniano com reclassificação efetivamente produzida pelo sistema nesta versão.',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'É o rótulo estrutural lacaniano efetivamente produzido hoje pelo sistema, reclassificando com vocabulário lacaniano as mesmas recorrências já trazidas pelo Motor Freud.',
            'fundamentacao_cientifica' => 'A Instância da Letra no Inconsciente ou a Razão desde Freud — ver Ontologia-Lacan.md §4 (tabela Deslocamento→Metonímia).',
            'dados_necessarios' => ['Recorrencia[] já produzida pelo DetectorRecorrencias'],
            'dados_opcionais' => ['OcorrenciaRecorrencia[] (circuito) — quando presente em ≥2 Sessões distintas, o rótulo passa a "circuito" em vez de "deslize metonímico" (revisão pós-Sprint 16, Peça C)'],
            'eventos_que_podem_origina_lo' => ['Recorrência já detectada pelo Motor Freud (≥2 ocorrências de conteúdo normalizado)'],
            'relacoes_com_outros_conceitos' => 'Par com Metáfora; releitura estrutural de Deslocamento (Ontologia-Freud.md).',
            'componentes' => ['Domain/Services/ReclassificadorLacaniano::reclassificar() / reclassificarComTrajeto()'],
            'observado_automaticamente' => 'Não (reclassifica dado já observado pelo Motor Freud, não observa por conta própria).',
            'organizado_automaticamente' => 'Sim (a reclassificação é, em si, uma forma de organização/rotulagem sobre dado já existente).',
            'classificado_automaticamente' => 'Sim — sempre como "Estrutura candidata: deslize metonímico." (ou variante de circuito), nunca afirmando estatuto de significante confirmado.',
            'depende_confirmacao_sujeito' => 'Não diretamente — só nas telas do analista.', 'depende_validacao_analista' => 'Sim.',
            'evidencias_produzidas' => ['Rótulo "Estrutura candidata: deslize metonímico." ou "...circuito — o tema retorna ao mesmo ponto através de sessões distintas."'],
            'limitacoes_computacionais' => 'Nunca afirma o estatuto de significante confirmado — permanece "estrutura candidata" (Ontologia-Lacan.md §5).',
            'trabalhos_relacionados' => ['A Instância da Letra no Inconsciente ou a Razão desde Freud', 'O Seminário sobre "A Carta Roubada"'],
            'motores_impactados' => ['Lacan Engine'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => [
                'interfere_na_conversa' => 'Não interfere na conversa — é uma reclassificação exclusiva das telas do analista (Regra 11).',
                'sujeito_pode_perceber' => 'Não.',
                'comportamento_da_ia' => 'A IA nunca menciona metonímia, deslize ou estrutura lacaniana ao Sujeito.',
                'perguntas_permitidas' => 'Nenhuma — este conceito não gera pergunta ao Sujeito nesta versão (a pergunta-eco pertence ao conceito de Repetição, não a este rótulo).',
                'perguntas_proibidas' => 'Qualquer pergunta que nomeie metonímia, significante ou estrutura lacaniana.',
            ],
            'visao_analista' => [
                'como_e_apresentado' => 'Apresentado como rótulo "Estrutura candidata: deslize metonímico." (ou variante de circuito) ao lado de cada recorrência, na tela de Observações.',
                'visualizacoes_produzidas' => 'Coluna "Leitura Lacaniana" na tela de Observações; rótulo no grafo do circuito quando aplicável.',
                'relacoes_exibidas' => 'A recorrência de base (Motor Freud) e, quando em ≥2 Sessões, o circuito correspondente.',
                'evidencias_que_sustentam' => ['Rótulo textual de ReclassificadorLacaniano'],
                'motores_que_produzem' => ['Lacan Engine'],
                'componentes_participantes' => ['ReclassificadorLacaniano', 'ObservacoesSujeitoController', 'observacoes/mostrar.php'],
            ],
        ],
    ],
    [
        'autor' => 'Jacques Lacan', 'conceito' => 'Registro Simbólico', 'obra_origem' => 'Função e Campo da Palavra e da Linguagem em Psicanálise',
        'ano' => '1953', 'idioma' => 'Francês', 'area' => 'Lacan',
        'conceitos_relacionados' => ['Registro Imaginário', 'Registro Real', 'Significante'],
        'autores_relacionados' => [], 'obras_relacionadas' => ['Função e Campo da Palavra e da Linguagem em Psicanálise', 'R.S.I. (Seminário XXII)'],
        'status' => 'Catalogado', 'observacoes' => 'Um dos três registros (RSI) — ver também Registro Imaginário e Registro Real.',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'Nenhum implementado nesta versão.',
            'fundamentacao_cientifica' => 'Função e Campo da Palavra e da Linguagem em Psicanálise (Lacan, 1953) — ver Ontologia-Lacan.md §3.5.',
            'dados_necessarios' => [], 'dados_opcionais' => [], 'eventos_que_podem_origina_lo' => [],
            'relacoes_com_outros_conceitos' => 'Tríade RSI com Registro Imaginário e Registro Real (Ontologia-Lacan.md §4).',
            'componentes' => [],
            'observado_automaticamente' => 'Não.', 'organizado_automaticamente' => 'Não.', 'classificado_automaticamente' => 'Não.',
            'depende_confirmacao_sujeito' => 'Sim.', 'depende_validacao_analista' => 'Sim.', 'evidencias_produzidas' => [],
            'limitacoes_computacionais' => 'Roadmap.md "Sprints futuras" — os Nós Borromeanos (RSI) não têm, nesta versão, base ontológica ou estrutural definida.',
            'trabalhos_relacionados' => ['Função e Campo da Palavra e da Linguagem em Psicanálise', 'R.S.I. (Seminário XXII)'],
            'motores_impactados' => ['Nenhum'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => array_merge($naoImplementadoSujeito, [
                'interfere_na_conversa' => 'Não interfere — nenhuma representação computacional existe.',
                'comportamento_da_ia' => 'Nenhum comportamento é derivado deste conceito.',
                'perguntas_proibidas' => 'Qualquer pergunta que pressuponha localizar a fala do Sujeito num registro (Simbólico/Imaginário/Real).',
            ]),
            'visao_analista' => $naoImplementadoAnalista,
        ],
    ],
    [
        'autor' => 'Jacques Lacan', 'conceito' => 'Registro Imaginário', 'obra_origem' => 'O Estádio do Espelho como Formador da Função do Eu',
        'ano' => '1949', 'idioma' => 'Francês', 'area' => 'Lacan',
        'conceitos_relacionados' => ['Registro Simbólico', 'Registro Real', 'Outro'],
        'autores_relacionados' => [], 'obras_relacionadas' => ['O Estádio do Espelho como Formador da Função do Eu', 'A Agressividade em Psicanálise'],
        'status' => 'Catalogado', 'observacoes' => 'Um dos três registros (RSI).',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'Nenhum implementado nesta versão.',
            'fundamentacao_cientifica' => 'O Estádio do Espelho como Formador da Função do Eu (Lacan, 1949) — ver Ontologia-Lacan.md §3.6.',
            'dados_necessarios' => [], 'dados_opcionais' => [], 'eventos_que_podem_origina_lo' => [],
            'relacoes_com_outros_conceitos' => 'Tríade RSI com Registro Simbólico e Registro Real (Ontologia-Lacan.md §4).',
            'componentes' => [],
            'observado_automaticamente' => 'Não.', 'organizado_automaticamente' => 'Não.', 'classificado_automaticamente' => 'Não.',
            'depende_confirmacao_sujeito' => 'Sim.', 'depende_validacao_analista' => 'Sim.', 'evidencias_produzidas' => [],
            'limitacoes_computacionais' => 'Roadmap.md "Sprints futuras" — os Nós Borromeanos (RSI) não têm, nesta versão, base ontológica ou estrutural definida.',
            'trabalhos_relacionados' => ['O Estádio do Espelho como Formador da Função do Eu', 'A Agressividade em Psicanálise'],
            'motores_impactados' => ['Nenhum'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => array_merge($naoImplementadoSujeito, [
                'interfere_na_conversa' => 'Não interfere — nenhuma representação computacional existe.',
                'comportamento_da_ia' => 'Nenhum comportamento é derivado deste conceito.',
                'perguntas_proibidas' => 'Qualquer pergunta que pressuponha localizar a fala do Sujeito num registro (Simbólico/Imaginário/Real).',
            ]),
            'visao_analista' => $naoImplementadoAnalista,
        ],
    ],
    [
        'autor' => 'Jacques Lacan', 'conceito' => 'Registro Real', 'obra_origem' => 'A Ética da Psicanálise (Seminário VII)',
        'ano' => '1959–1960', 'idioma' => 'Francês', 'area' => 'Lacan',
        'conceitos_relacionados' => ['Registro Simbólico', 'Registro Imaginário', 'Objeto a'],
        'autores_relacionados' => [], 'obras_relacionadas' => ['A Ética da Psicanálise (Seminário VII)', 'R.S.I. (Seminário XXII)'],
        'status' => 'Catalogado', 'observacoes' => 'Um dos três registros (RSI); ver também Documento-Mestre.md §6.6.',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'Nenhum implementado nesta versão.',
            'fundamentacao_cientifica' => 'A Ética da Psicanálise, Seminário VII (Lacan, 1959–1960), conceito de Das Ding — ver Ontologia-Lacan.md §3.7.',
            'dados_necessarios' => [], 'dados_opcionais' => [], 'eventos_que_podem_origina_lo' => [],
            'relacoes_com_outros_conceitos' => 'Tríade RSI com Registro Simbólico e Registro Imaginário (Ontologia-Lacan.md §4).',
            'componentes' => [],
            'observado_automaticamente' => 'Não.', 'organizado_automaticamente' => 'Não.', 'classificado_automaticamente' => 'Não.',
            'depende_confirmacao_sujeito' => 'Sim.', 'depende_validacao_analista' => 'Sim.', 'evidencias_produzidas' => [],
            'limitacoes_computacionais' => 'Roadmap.md "Sprints futuras" — os Nós Borromeanos (RSI) não têm, nesta versão, base ontológica ou estrutural definida; é a única das cinco formalizações adiadas que provavelmente não cabe em nó/aresta simples.',
            'trabalhos_relacionados' => ['A Ética da Psicanálise (Seminário VII)', 'R.S.I. (Seminário XXII)'],
            'motores_impactados' => ['Nenhum'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => array_merge($naoImplementadoSujeito, [
                'interfere_na_conversa' => 'Não interfere — nenhuma representação computacional existe.',
                'comportamento_da_ia' => 'Nenhum comportamento é derivado deste conceito.',
                'perguntas_proibidas' => 'Qualquer pergunta que pressuponha localizar a fala do Sujeito num registro (Simbólico/Imaginário/Real).',
            ]),
            'visao_analista' => $naoImplementadoAnalista,
        ],
    ],
    [
        'autor' => 'Jacques Lacan', 'conceito' => 'Outro', 'obra_origem' => 'Subversão do Sujeito e Dialética do Desejo no Inconsciente Freudiano',
        'ano' => '1960', 'idioma' => 'Francês', 'area' => 'Lacan',
        'conceitos_relacionados' => ['Objeto a', 'Desejo lacaniano', 'Falta'],
        'autores_relacionados' => [], 'obras_relacionadas' => ['Subversão do Sujeito e Dialética do Desejo no Inconsciente Freudiano', 'De um Outro ao outro (Seminário XVI)'],
        'status' => 'Catalogado', 'observacoes' => '',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'Nenhum implementado nesta versão.',
            'fundamentacao_cientifica' => 'Subversão do Sujeito e Dialética do Desejo no Inconsciente Freudiano (Lacan, 1960) — ver Ontologia-Lacan.md §3.8.',
            'dados_necessarios' => [], 'dados_opcionais' => [], 'eventos_que_podem_origina_lo' => [],
            'relacoes_com_outros_conceitos' => 'Articulado a Objeto a, Falta e Desejo lacaniano (Ontologia-Lacan.md §4); dialoga com a Transferência freudiana (dirigida ao Outro).',
            'componentes' => [],
            'observado_automaticamente' => 'Não.', 'organizado_automaticamente' => 'Não.', 'classificado_automaticamente' => 'Não.',
            'depende_confirmacao_sujeito' => 'Sim.', 'depende_validacao_analista' => 'Sim.', 'evidencias_produzidas' => [],
            'limitacoes_computacionais' => 'Ontologia-Lacan.md §5 — nenhuma representação computacional definida.',
            'trabalhos_relacionados' => ['Subversão do Sujeito e Dialética do Desejo no Inconsciente Freudiano', 'De um Outro ao outro (Seminário XVI)'],
            'motores_impactados' => ['Nenhum'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => array_merge($naoImplementadoSujeito, [
                'interfere_na_conversa' => 'Não interfere — nenhuma representação computacional existe.',
                'comportamento_da_ia' => 'Nenhum comportamento é derivado deste conceito.',
                'perguntas_proibidas' => 'Qualquer pergunta que nomeie o Outro lacaniano ou pressuponha posição do Sujeito em relação a ele.',
            ]),
            'visao_analista' => $naoImplementadoAnalista,
        ],
    ],
    [
        'autor' => 'Jacques Lacan', 'conceito' => 'Objeto a', 'obra_origem' => 'A Angústia (Seminário X)',
        'ano' => '1962–1963', 'idioma' => 'Francês', 'area' => 'Lacan',
        'conceitos_relacionados' => ['Falta', 'Outro', 'Desejo lacaniano'],
        'autores_relacionados' => [], 'obras_relacionadas' => ['A Angústia (Seminário X)', 'A Transferência (Seminário VIII)'],
        'status' => 'Catalogado', 'observacoes' => '',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'Nenhum implementado nesta versão.',
            'fundamentacao_cientifica' => 'A Angústia, Seminário X (Lacan, 1962–1963) — ver Ontologia-Lacan.md §3.9.',
            'dados_necessarios' => [], 'dados_opcionais' => [], 'eventos_que_podem_origina_lo' => [],
            'relacoes_com_outros_conceitos' => 'Articulado a Falta, Outro e Desejo lacaniano (Ontologia-Lacan.md §4).',
            'componentes' => [],
            'observado_automaticamente' => 'Não.', 'organizado_automaticamente' => 'Não.', 'classificado_automaticamente' => 'Não.',
            'depende_confirmacao_sujeito' => 'Sim.', 'depende_validacao_analista' => 'Sim.', 'evidencias_produzidas' => [],
            'limitacoes_computacionais' => 'Ontologia-Lacan.md §5 — nenhuma representação computacional definida; parte do formalismo do Grafo do Desejo, adiado em Roadmap.md "Sprints futuras".',
            'trabalhos_relacionados' => ['A Angústia (Seminário X)', 'A Transferência (Seminário VIII)'],
            'motores_impactados' => ['Nenhum'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => array_merge($naoImplementadoSujeito, [
                'interfere_na_conversa' => 'Não interfere — nenhuma representação computacional existe.',
                'comportamento_da_ia' => 'Nenhum comportamento é derivado deste conceito.',
                'perguntas_proibidas' => 'Qualquer pergunta que nomeie objeto a ou pressuponha identificá-lo na fala do Sujeito.',
            ]),
            'visao_analista' => $naoImplementadoAnalista,
        ],
    ],
    [
        'autor' => 'Jacques Lacan', 'conceito' => 'Falta', 'obra_origem' => 'A Relação de Objeto (Seminário IV)',
        'ano' => '1956–1957', 'idioma' => 'Francês', 'area' => 'Lacan',
        'conceitos_relacionados' => ['Objeto a', 'Desejo lacaniano', 'Falo'],
        'autores_relacionados' => [], 'obras_relacionadas' => ['A Relação de Objeto (Seminário IV)', 'A Significação do Falo'],
        'status' => 'Catalogado', 'observacoes' => '',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'Nenhum implementado nesta versão.',
            'fundamentacao_cientifica' => 'A Relação de Objeto, Seminário IV (Lacan, 1956–1957) — ver Ontologia-Lacan.md §3.10.',
            'dados_necessarios' => [], 'dados_opcionais' => [], 'eventos_que_podem_origina_lo' => [],
            'relacoes_com_outros_conceitos' => 'Articulada a Objeto a e Desejo lacaniano (Ontologia-Lacan.md §4).',
            'componentes' => [],
            'observado_automaticamente' => 'Não.', 'organizado_automaticamente' => 'Não.', 'classificado_automaticamente' => 'Não.',
            'depende_confirmacao_sujeito' => 'Sim.', 'depende_validacao_analista' => 'Sim.', 'evidencias_produzidas' => [],
            'limitacoes_computacionais' => 'Ontologia-Lacan.md §5 — nenhuma representação computacional definida.',
            'trabalhos_relacionados' => ['A Relação de Objeto (Seminário IV)', 'A Significação do Falo'],
            'motores_impactados' => ['Nenhum'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => array_merge($naoImplementadoSujeito, [
                'interfere_na_conversa' => 'Não interfere — nenhuma representação computacional existe.',
                'comportamento_da_ia' => 'Nenhum comportamento é derivado deste conceito.',
                'perguntas_proibidas' => 'Qualquer pergunta que nomeie a falta lacaniana ou pressuponha localizá-la na fala do Sujeito.',
            ]),
            'visao_analista' => $naoImplementadoAnalista,
        ],
    ],
    [
        'autor' => 'Jacques Lacan', 'conceito' => 'Desejo lacaniano', 'obra_origem' => 'Subversão do Sujeito e Dialética do Desejo no Inconsciente Freudiano',
        'ano' => '1960', 'idioma' => 'Francês', 'area' => 'Lacan',
        'conceitos_relacionados' => ['Falta', 'Objeto a', 'Outro'],
        'autores_relacionados' => [], 'obras_relacionadas' => ['Subversão do Sujeito e Dialética do Desejo no Inconsciente Freudiano', 'O Desejo e sua Interpretação (Seminário VI)'],
        'status' => 'Catalogado', 'observacoes' => 'Distinto do Desejo freudiano (Conceitos/desejo-freud.md) — nota de escopo em Ontologia-Freud.md §3.4, articulada em Ontologia-Lacan.md.',
        'aplicacao_computacional' => [
            'objetivo_computacional' => 'Nenhum implementado nesta versão — reformulação lacaniana distinta do Desejo freudiano, sem correlato computacional definido.',
            'fundamentacao_cientifica' => 'Subversão do Sujeito e Dialética do Desejo no Inconsciente Freudiano (Lacan, 1960); O Desejo e sua Interpretação, Seminário VI — ver Ontologia-Lacan.md §3.11.',
            'dados_necessarios' => [], 'dados_opcionais' => [], 'eventos_que_podem_origina_lo' => [],
            'relacoes_com_outros_conceitos' => 'Articulado a Falta, Objeto a e Outro; formalizado no Grafo do Desejo (Ontologia-Lacan.md §4).',
            'componentes' => [],
            'observado_automaticamente' => 'Não.', 'organizado_automaticamente' => 'Não.', 'classificado_automaticamente' => 'Não.',
            'depende_confirmacao_sujeito' => 'Sim.', 'depende_validacao_analista' => 'Sim.', 'evidencias_produzidas' => [],
            'limitacoes_computacionais' => 'Ontologia-Lacan.md §5; o Grafo do Desejo — o mais complexo dos formalismos lacanianos — está registrado em Roadmap.md "Sprints futuras" sem nenhuma base ontológica ou estrutural ainda.',
            'trabalhos_relacionados' => ['Subversão do Sujeito e Dialética do Desejo no Inconsciente Freudiano', 'O Desejo e sua Interpretação (Seminário VI)'],
            'motores_impactados' => ['Nenhum'],
        ],
        'representacao_computacional' => [
            'visao_sujeito' => array_merge($naoImplementadoSujeito, [
                'interfere_na_conversa' => 'Não interfere — nenhuma representação computacional existe; a continuidade da conversa (Motor de Enunciação Socrática) usa apenas turnos recentes, sem modelar desejo lacaniano.',
                'comportamento_da_ia' => 'Nenhum comportamento é derivado deste conceito.',
                'perguntas_proibidas' => 'Qualquer pergunta que nomeie o desejo lacaniano, falta ou objeto a para o Sujeito.',
            ]),
            'visao_analista' => $naoImplementadoAnalista,
        ],
    ],
];
