<?php
declare(strict_types=1);

/**
 * Dataset — catálogo completo das obras de Sigmund Freud usado pelo gerador
 * da Biblioteca Teórica. "Motores do PsycheAI relacionados" só cita um
 * motor quando a obra já é referência explícita de Ontologia-Freud.md §6
 * (núcleo dos dez conceitos) ou tem cruzamento estrutural direto e
 * amplamente reconhecido com a releitura lacaniana; nas demais obras o
 * campo é "Nenhum (catalogação apenas)" — catalogadas para completude do
 * corpus, sem reivindicar uso computacional que ainda não existe.
 */

const FE = 'Freud Engine';
const LE = 'Lacan Engine';
const NENHUM = ['Nenhum (catalogação apenas)'];

return [
    // --- 1893-1899: período pré-psicanalítico e primeiras formulações ---
    [
        'autor' => 'Sigmund Freud (com Josef Breuer)',
        'titulo' => 'Sobre o Mecanismo Psíquico dos Fenômenos Histéricos: Comunicação Preliminar',
        'original' => 'Über den psychischen Mechanismus hysterischer Phänomene: Vorläufige Mitteilung',
        'ano' => '1893',
        'idioma' => 'Alemão',
        'tipo' => 'Artigo Técnico',
        'area' => 'Freud',
        'conceitos' => ['Trauma psíquico', 'Catarse', 'Afeto estrangulado'],
        'autores_relacionados' => ['Josef Breuer', 'Jean-Martin Charcot'],
        'obras_relacionadas' => ['Estudos sobre a Histeria'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Texto que abre Estudos sobre a Histeria (1895); catalogado separadamente por ser frequentemente citado de forma autônoma na bibliografia freudiana.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Charcot',
        'original' => 'Charcot',
        'ano' => '1893',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Hipnose', 'Histeria'],
        'autores_relacionados' => ['Jean-Martin Charcot'],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'A verificar',
        'observacoes' => 'Necrológio publicado por Freud após a morte de Charcot; data de publicação a confirmar contra a edição de referência adotada.',
    ],
    [
        'autor' => 'Sigmund Freud (com Josef Breuer)',
        'titulo' => 'As Neuropsicoses de Defesa',
        'original' => 'Die Abwehr-Neuropsychosen',
        'ano' => '1894',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Defesa', 'Recalque (formulação inicial)'],
        'autores_relacionados' => ['Josef Breuer'],
        'obras_relacionadas' => ['A Repressão (O Recalque)'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Primeira formulação do conceito de defesa, precursor do conceito de recalque de 1915.',
    ],
    [
        'autor' => 'Sigmund Freud e Josef Breuer',
        'titulo' => 'Estudos sobre a Histeria',
        'original' => 'Studien über Hysterie',
        'ano' => '1895',
        'idioma' => 'Alemão',
        'tipo' => 'Livro',
        'area' => 'Freud',
        'conceitos' => ['Histeria', 'Catarse', 'Trauma psíquico', 'Método catártico'],
        'autores_relacionados' => ['Josef Breuer'],
        'obras_relacionadas' => ['Sobre o Mecanismo Psíquico dos Fenômenos Histéricos: Comunicação Preliminar'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Obra fundacional do método catártico, anterior à psicanálise propriamente dita.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Rascunho de uma Psicologia Científica',
        'original' => 'Entwurf einer Psychologie',
        'ano' => '1895 (publicado postumamente em 1950)',
        'idioma' => 'Alemão',
        'tipo' => 'Carta',
        'area' => 'Freud',
        'conceitos' => ['Aparelho psíquico', 'Neurônio', 'Princípio de constância'],
        'autores_relacionados' => ['Wilhelm Fliess'],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Manuscrito enviado a Fliess, não publicado por Freud em vida; publicado postumamente como parte da correspondência com Fliess.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'A Hereditariedade e a Etiologia das Neuroses',
        'original' => "L'hérédité et l'étiologie des névroses",
        'ano' => '1896',
        'idioma' => 'Francês',
        'tipo' => 'Artigo Técnico',
        'area' => 'Freud',
        'conceitos' => ['Etiologia sexual das neuroses'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['A Etiologia da Histeria'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Publicado originalmente em francês.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Novas Observações sobre as Neuropsicoses de Defesa',
        'original' => 'Weitere Bemerkungen über die Abwehr-Neuropsychosen',
        'ano' => '1896',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Defesa', 'Fantasia'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['As Neuropsicoses de Defesa'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'A Etiologia da Histeria',
        'original' => 'Zur Ätiologie der Hysterie',
        'ano' => '1896',
        'idioma' => 'Alemão',
        'tipo' => 'Conferência',
        'area' => 'Freud',
        'conceitos' => ['Teoria da sedução', 'Etiologia sexual das neuroses'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Formulação da chamada "teoria da sedução", posteriormente revista por Freud.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'A Sexualidade na Etiologia das Neuroses',
        'original' => 'Die Sexualität in der Ätiologie der Neurosen',
        'ano' => '1898',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Etiologia sexual das neuroses'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Três Ensaios sobre a Teoria da Sexualidade'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],

    // --- 1900-1905: fundação da psicanálise ---
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'A Interpretação dos Sonhos',
        'original' => 'Die Traumdeutung',
        'ano' => '1900',
        'idioma' => 'Alemão',
        'tipo' => 'Livro',
        'area' => 'Freud',
        'conceitos' => ['Sonhos', 'Desejo', 'Condensação', 'Deslocamento', 'Elaboração secundária', 'Inconsciente'],
        'autores_relacionados' => ['Jacques Lacan'],
        'obras_relacionadas' => ['Sobre os Sonhos', 'Complemento Metapsicológico à Teoria dos Sonhos'],
        'motores' => [FE, LE],
        'status' => 'Catalogado',
        'observacoes' => 'Citada em Ontologia-Freud.md §6 como obra relacionada ao conceito de Desejo e ao de Sonhos.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Sobre os Sonhos',
        'original' => 'Über den Traum',
        'ano' => '1901',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Sonhos', 'Trabalho do sonho'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['A Interpretação dos Sonhos'],
        'motores' => [FE],
        'status' => 'Catalogado',
        'observacoes' => 'Versão resumida e mais acessível de A Interpretação dos Sonhos.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Psicopatologia da Vida Cotidiana',
        'original' => 'Zur Psychopathologie des Alltagslebens',
        'ano' => '1901',
        'idioma' => 'Alemão',
        'tipo' => 'Livro',
        'area' => 'Freud',
        'conceitos' => ['Ato falho', 'Formação de compromisso', 'Esquecimento'],
        'autores_relacionados' => ['Jacques Lacan'],
        'obras_relacionadas' => [],
        'motores' => [FE, LE],
        'status' => 'Catalogado',
        'observacoes' => 'Citada em Ontologia-Freud.md §6 como obra relacionada à Formação de compromisso e ao Ato falho.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'O Método Psicanalítico de Freud',
        'original' => "Die Freud'sche psychoanalytische Methode",
        'ano' => '1904',
        'idioma' => 'Alemão',
        'tipo' => 'Artigo Técnico',
        'area' => 'Freud',
        'conceitos' => ['Técnica psicanalítica'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Fragmento da Análise de um Caso de Histeria (Caso Dora)',
        'original' => 'Bruchstück einer Hysterie-Analyse',
        'ano' => '1905 (redigido em 1901)',
        'idioma' => 'Alemão',
        'tipo' => 'Caso Clínico',
        'area' => 'Freud',
        'conceitos' => ['Histeria', 'Transferência', 'Sonhos'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['A Dinâmica da Transferência'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Primeiro dos cinco grandes casos clínicos publicados por Freud.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Três Ensaios sobre a Teoria da Sexualidade',
        'original' => 'Drei Abhandlungen zur Sexualtheorie',
        'ano' => '1905',
        'idioma' => 'Alemão',
        'tipo' => 'Livro',
        'area' => 'Freud',
        'conceitos' => ['Pulsão', 'Sexualidade infantil', 'Zonas erógenas', 'Objeto da pulsão'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Pulsões e seus Destinos'],
        'motores' => [FE],
        'status' => 'Catalogado',
        'observacoes' => 'Citada em Ontologia-Freud.md §6 como obra relacionada à Pulsão.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Os Chistes e sua Relação com o Inconsciente',
        'original' => 'Der Witz und seine Beziehung zum Unbewußten',
        'ano' => '1905',
        'idioma' => 'Alemão',
        'tipo' => 'Livro',
        'area' => 'Freud',
        'conceitos' => ['Chiste', 'Condensação', 'Deslocamento', 'Formação de compromisso'],
        'autores_relacionados' => ['Jacques Lacan'],
        'obras_relacionadas' => ['A Interpretação dos Sonhos'],
        'motores' => [FE, LE],
        'status' => 'Catalogado',
        'observacoes' => 'Citada em Ontologia-Freud.md §6 como obra relacionada ao Chiste.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Sobre Psicoterapia',
        'original' => 'Über Psychotherapie',
        'ano' => '1905',
        'idioma' => 'Alemão',
        'tipo' => 'Conferência',
        'area' => 'Freud',
        'conceitos' => ['Técnica psicanalítica'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Personagens Psicopáticos no Palco',
        'original' => 'Psychopathische Personen auf der Bühne',
        'ano' => 'c. 1905/1906 (publicado postumamente em 1942)',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Identificação', 'Culpa inconsciente'],
        'autores_relacionados' => ['Shakespeare'],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'A verificar',
        'observacoes' => 'Data de composição e publicação divergem entre fontes; manuscrito só publicado postumamente.',
    ],

    // --- 1906-1913: técnica, casos clínicos, aplicações ---
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'A Psicanálise e a Determinação dos Fatos em Processos Jurídicos',
        'original' => 'Tatbestandsdiagnostik und Psychoanalyse',
        'ano' => '1906',
        'idioma' => 'Alemão',
        'tipo' => 'Artigo Técnico',
        'area' => 'Freud',
        'conceitos' => ['Associação livre'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Minha Opinião sobre o Papel da Sexualidade na Etiologia das Neuroses',
        'original' => 'Meine Ansichten über die Rolle der Sexualität in der Ätiologie der Neurosen',
        'ano' => '1906',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Etiologia sexual das neuroses'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Três Ensaios sobre a Teoria da Sexualidade'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Delírio e Sonhos na Gradiva de Jensen',
        'original' => "Der Wahn und die Träume in W. Jensens 'Gradiva'",
        'ano' => '1907',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Delírio', 'Sonhos', 'Retorno do recalcado'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['A Interpretação dos Sonhos'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Primeiro grande ensaio de Freud sobre uma obra literária.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Atos Obsessivos e Práticas Religiosas',
        'original' => 'Zwangshandlungen und Religionsübungen',
        'ano' => '1907',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Neurose obsessiva', 'Ritual'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Totem e Tabu'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Caráter e Erotismo Anal',
        'original' => 'Charakter und Analerotik',
        'ano' => '1908',
        'idioma' => 'Alemão',
        'tipo' => 'Artigo Técnico',
        'area' => 'Freud',
        'conceitos' => ['Erotismo anal', 'Formação de caráter'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Três Ensaios sobre a Teoria da Sexualidade'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => "Moral Sexual 'Civilizada' e Doença Nervosa Moderna",
        'original' => "'Die' kulturelle Sexualmoral und die moderne Nervosität",
        'ano' => '1908',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Recalque cultural', 'Neurose'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Mal-estar na Civilização'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Escritores Criativos e Devaneio',
        'original' => 'Der Dichter und das Phantasieren',
        'ano' => '1908',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Fantasia', 'Desejo', 'Sublimação'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'As Fantasias Histéricas e sua Relação com a Bissexualidade',
        'original' => 'Hysterische Phantasien und ihre Beziehung zur Bisexualität',
        'ano' => '1908',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Fantasia', 'Histeria'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'O Romance Familiar dos Neuróticos',
        'original' => 'Der Familienroman der Neurotiker',
        'ano' => '1909',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Fantasia', 'Complexo de Édipo'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Análise de uma Fobia em um Menino de Cinco Anos (Caso Pequeno Hans)',
        'original' => 'Analyse der Phobie eines fünfjährigen Knaben',
        'ano' => '1909',
        'idioma' => 'Alemão',
        'tipo' => 'Caso Clínico',
        'area' => 'Freud',
        'conceitos' => ['Fobia', 'Complexo de Édipo', 'Angústia de castração'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['A Dissolução do Complexo de Édipo'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Notas sobre um Caso de Neurose Obsessiva (O Homem dos Ratos)',
        'original' => 'Bemerkungen über einen Fall von Zwangsneurose',
        'ano' => '1909',
        'idioma' => 'Alemão',
        'tipo' => 'Caso Clínico',
        'area' => 'Freud',
        'conceitos' => ['Neurose obsessiva', 'Ambivalência'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Cinco Lições de Psicanálise',
        'original' => 'Über Psychoanalyse',
        'ano' => '1910',
        'idioma' => 'Alemão',
        'tipo' => 'Conferência',
        'area' => 'Freud',
        'conceitos' => ['Introdução à psicanálise'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Conferências Introdutórias sobre Psicanálise'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Ciclo de conferências proferidas na Clark University (EUA).',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Leonardo da Vinci e uma Lembrança de sua Infância',
        'original' => 'Eine Kindheitserinnerung des Leonardo da Vinci',
        'ano' => '1910',
        'idioma' => 'Alemão',
        'tipo' => 'Livro',
        'area' => 'Freud',
        'conceitos' => ['Sublimação', 'Narcisismo'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Sobre um Tipo Especial de Escolha de Objeto no Homem',
        'original' => 'Über einen besonderen Typus der Objektwahl beim Manne',
        'ano' => '1910',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Escolha de objeto', 'Complexo de Édipo'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Sobre a Degradação Geral da Vida Erótica', 'O Tabu da Virgindade'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Primeiro dos três ensaios reunidos como "Contribuições à Psicologia do Amor Erótico".',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Formulações sobre os Dois Princípios do Funcionamento Mental',
        'original' => 'Formulierungen über die zwei Prinzipien des psychischen Geschehens',
        'ano' => '1911',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Princípio do prazer', 'Princípio de realidade'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Além do Princípio do Prazer'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Notas Psicanalíticas sobre um Relato Autobiográfico de um Caso de Paranoia (Caso Schreber)',
        'original' => 'Psychoanalytische Bemerkungen über einen autobiographisch beschriebenen Fall von Paranoia (Dementia paranoides)',
        'ano' => '1911',
        'idioma' => 'Alemão',
        'tipo' => 'Caso Clínico',
        'area' => 'Freud',
        'conceitos' => ['Paranoia', 'Projeção', 'Narcisismo'],
        'autores_relacionados' => ['Jacques Lacan'],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Único caso clínico de Freud baseado exclusivamente em texto autobiográfico do paciente, sem tratamento direto — Lacan retoma este caso em seu Seminário III.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Recomendações aos Médicos que Exercem a Psicanálise',
        'original' => 'Zur Ärztlichen Handhabung der Psychoanalyse',
        'ano' => '1912',
        'idioma' => 'Alemão',
        'tipo' => 'Artigo Técnico',
        'area' => 'Freud',
        'conceitos' => ['Atenção flutuante', 'Técnica psicanalítica'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Sobre o Início do Tratamento'],
        'motores' => [FE],
        'status' => 'Catalogado',
        'observacoes' => 'Formula o princípio de "atenção uniformemente flutuante", referido em Documento-Mestre.md §6.7 como base do modo de enunciação do PsycheAI.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'A Dinâmica da Transferência',
        'original' => 'Zur Dynamik der Übertragung',
        'ano' => '1912',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Transferência', 'Repetição'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Recordar, Repetir e Elaborar'],
        'motores' => [FE],
        'status' => 'Catalogado',
        'observacoes' => 'Citada em Ontologia-Freud.md §6 como obra relacionada à Transferência.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Sobre a Degradação Geral da Vida Erótica',
        'original' => 'Über die allgemeinste Erniedrigung des Liebeslebens',
        'ano' => '1912',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Escolha de objeto', 'Vida erótica'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Sobre um Tipo Especial de Escolha de Objeto no Homem', 'O Tabu da Virgindade'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Segundo dos três ensaios de "Contribuições à Psicologia do Amor Erótico".',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'O Tema dos Três Escrínios',
        'original' => 'Das Motiv der Kästchenwahl',
        'ano' => '1913',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Simbolismo', 'Escolha'],
        'autores_relacionados' => ['Shakespeare'],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Totem e Tabu',
        'original' => 'Totem und Tabu',
        'ano' => '1913',
        'idioma' => 'Alemão',
        'tipo' => 'Livro',
        'area' => 'Freud',
        'conceitos' => ['Tabu do incesto', 'Ambivalência', 'Complexo de Édipo', 'Mito do pai da horda'],
        'autores_relacionados' => ['Claude Lévi-Strauss'],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Primeira grande obra antropológica de Freud; dialoga posteriormente com a antropologia estrutural de Lévi-Strauss.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Sobre o Início do Tratamento',
        'original' => 'Zur Einleitung der Behandlung',
        'ano' => '1913',
        'idioma' => 'Alemão',
        'tipo' => 'Artigo Técnico',
        'area' => 'Freud',
        'conceitos' => ['Técnica psicanalítica', 'Associação livre'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Recomendações aos Médicos que Exercem a Psicanálise'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'O Interesse Científico da Psicanálise',
        'original' => 'Das Interesse an der Psychoanalyse',
        'ano' => '1913',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Psicanálise e outras ciências'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],

    // --- 1914-1917: metapsicologia, narcisismo, técnica ---
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'A História do Movimento Psicanalítico',
        'original' => 'Zur Geschichte der psychoanalytischen Bewegung',
        'ano' => '1914',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['História da psicanálise'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Sobre o Narcisismo: uma Introdução',
        'original' => 'Zur Einführung des Narzißmus',
        'ano' => '1914',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Narcisismo', 'Ideal do eu', 'Libido do eu'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['O Ego e o Id'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Introduz o conceito de narcisismo, condição para a formulação posterior da segunda tópica.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Recordar, Repetir e Elaborar',
        'original' => 'Erinnern, Wiederholen und Durcharbeiten',
        'ano' => '1914',
        'idioma' => 'Alemão',
        'tipo' => 'Artigo Técnico',
        'area' => 'Freud',
        'conceitos' => ['Repetição', 'Transferência', 'Elaboração'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['A Dinâmica da Transferência'],
        'motores' => [FE],
        'status' => 'Catalogado',
        'observacoes' => 'Citada em Ontologia-Freud.md §6 como obra relacionada à Transferência.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'O Moisés de Michelangelo',
        'original' => 'Der Moses des Michelangelo',
        'ano' => '1914',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Interpretação de obra de arte'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Moisés e o Monoteísmo'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Pulsões e seus Destinos',
        'original' => 'Triebe und Triebschicksale',
        'ano' => '1915',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Pulsão', 'Fonte', 'Pressão', 'Finalidade', 'Objeto'],
        'autores_relacionados' => ['Jacques Lacan'],
        'obras_relacionadas' => ['Três Ensaios sobre a Teoria da Sexualidade'],
        'motores' => [FE, LE],
        'status' => 'Catalogado',
        'observacoes' => 'Citada em Ontologia-Freud.md §6 como obra relacionada à Pulsão; ensaio metapsicológico central para a releitura lacaniana da pulsão.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'A Repressão (O Recalque)',
        'original' => 'Die Verdrängung',
        'ano' => '1915',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Recalque', 'Retorno do recalcado'],
        'autores_relacionados' => ['Jacques Lacan'],
        'obras_relacionadas' => ['O Inconsciente'],
        'motores' => [FE, LE],
        'status' => 'Catalogado',
        'observacoes' => 'Citada em Ontologia-Freud.md §6 como obra relacionada ao Recalque.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'O Inconsciente',
        'original' => 'Das Unbewußte',
        'ano' => '1915',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Inconsciente', 'Processo primário', 'Representante psíquico'],
        'autores_relacionados' => ['Jacques Lacan'],
        'obras_relacionadas' => ['A Repressão (O Recalque)'],
        'motores' => [FE, LE],
        'status' => 'Catalogado',
        'observacoes' => 'Citada em Ontologia-Freud.md §6 como obra relacionada ao Inconsciente; um dos textos metapsicológicos mais retomados por Lacan.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Observações sobre o Amor de Transferência',
        'original' => 'Bemerkungen über die Übertragungsliebe',
        'ano' => '1915',
        'idioma' => 'Alemão',
        'tipo' => 'Artigo Técnico',
        'area' => 'Freud',
        'conceitos' => ['Transferência', 'Amor de transferência'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['A Dinâmica da Transferência'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Reflexões para os Tempos de Guerra e Morte',
        'original' => 'Zeitgemäßes über Krieg und Tod',
        'ano' => '1915',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Pulsão de morte (formulação inicial)', 'Civilização'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Além do Princípio do Prazer'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Sobre a Transitoriedade',
        'original' => 'Vergänglichkeit',
        'ano' => '1916',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Luto', 'Valor estético'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Luto e Melancolia'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Ensaio breve, redigido a partir de uma conversa com Rainer Maria Rilke.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Alguns Tipos de Caráter Encontrados no Trabalho Psicanalítico',
        'original' => 'Einige Charaktertypen aus der psychoanalytischen Arbeit',
        'ano' => '1916',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Formação de caráter', 'Culpa inconsciente'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Conferências Introdutórias sobre Psicanálise',
        'original' => 'Vorlesungen zur Einführung in die Psychoanalyse',
        'ano' => '1916–1917',
        'idioma' => 'Alemão',
        'tipo' => 'Livro',
        'area' => 'Freud',
        'conceitos' => ['Ato falho', 'Sonhos', 'Teoria geral das neuroses'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Novas Conferências Introdutórias sobre Psicanálise'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Curso de conferências proferido na Universidade de Viena.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Uma Dificuldade no Caminho da Psicanálise',
        'original' => 'Eine Schwierigkeit der Psychoanalyse',
        'ano' => '1917',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Narcisismo ferido', 'Inconsciente'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Complemento Metapsicológico à Teoria dos Sonhos',
        'original' => 'Ergänzung zur Traumlehre',
        'ano' => '1917',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Sonhos', 'Narcisismo', 'Regressão'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['A Interpretação dos Sonhos'],
        'motores' => [FE],
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Luto e Melancolia',
        'original' => 'Trauer und Melancholie',
        'ano' => '1917',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Luto', 'Melancolia', 'Identificação', 'Perda de objeto'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['O Ego e o Id'],
        'motores' => [FE],
        'status' => 'Catalogado',
        'observacoes' => 'Ensaio metapsicológico central para a segunda tópica, publicado no mesmo grupo dos demais textos metapsicológicos de 1915.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Sobre as Transformações das Pulsões, Especialmente do Erotismo Anal',
        'original' => 'Über Triebumsetzungen, insbesondere der Analerotik',
        'ano' => '1917',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Erotismo anal', 'Simbolismo'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Caráter e Erotismo Anal'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'O Tabu da Virgindade',
        'original' => 'Das Tabu der Virginität',
        'ano' => '1918',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Tabu', 'Vida erótica feminina'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Sobre um Tipo Especial de Escolha de Objeto no Homem', 'Sobre a Degradação Geral da Vida Erótica'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Terceiro dos três ensaios de "Contribuições à Psicologia do Amor Erótico".',
    ],

    // --- 1918-1923: virada pulsional, segunda tópica ---
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Da História de uma Neurose Infantil (O Homem dos Lobos)',
        'original' => 'Aus der Geschichte einer infantilen Neurose',
        'ano' => '1918 (redigido em 1914)',
        'idioma' => 'Alemão',
        'tipo' => 'Caso Clínico',
        'area' => 'Freud',
        'conceitos' => ['Cena primária', 'Neurose infantil', 'Sonho'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Último dos cinco grandes casos clínicos publicados por Freud.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Linhas de Progresso na Terapia Psicanalítica',
        'original' => 'Wege der psychoanalytischen Therapie',
        'ano' => '1919',
        'idioma' => 'Alemão',
        'tipo' => 'Conferência',
        'area' => 'Freud',
        'conceitos' => ['Técnica psicanalítica'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'O Estranho',
        'original' => 'Das Unheimliche',
        'ano' => '1919',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Estranho familiar', 'Retorno do recalcado', 'Duplo'],
        'autores_relacionados' => ['Jacques Lacan'],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Conceito retomado por Lacan em referência ao registro Real; não incluído nesta versão entre os motores por ainda não ter obra freudiana correspondente citada em Ontologia-Freud.md.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Uma Criança é Espancada',
        'original' => 'Ein Kind wird geschlagen',
        'ano' => '1919',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Fantasia', 'Masoquismo', 'Complexo de Édipo'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['O Problema Econômico do Masoquismo'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Além do Princípio do Prazer',
        'original' => 'Jenseits des Lustprinzips',
        'ano' => '1920',
        'idioma' => 'Alemão',
        'tipo' => 'Livro',
        'area' => 'Freud',
        'conceitos' => ['Repetição', 'Pulsão de morte', 'Compulsão à repetição'],
        'autores_relacionados' => ['Jacques Lacan'],
        'obras_relacionadas' => [],
        'motores' => [FE, LE],
        'status' => 'Catalogado',
        'observacoes' => 'Citada em Ontologia-Freud.md §6 como obra relacionada à Repetição.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Sobre a Psicogênese de um Caso de Homossexualismo Feminino',
        'original' => 'Über die Psychogenese eines Falles von weiblicher Homosexualität',
        'ano' => '1920',
        'idioma' => 'Alemão',
        'tipo' => 'Caso Clínico',
        'area' => 'Freud',
        'conceitos' => ['Escolha de objeto', 'Complexo de Édipo'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Psicologia de Grupo e Análise do Ego',
        'original' => 'Massenpsychologie und Ich-Analyse',
        'ano' => '1921',
        'idioma' => 'Alemão',
        'tipo' => 'Livro',
        'area' => 'Freud',
        'conceitos' => ['Identificação', 'Ideal do eu', 'Laço social'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['O Ego e o Id'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Sobre Alguns Mecanismos Neuróticos no Ciúme, Paranoia e Homossexualidade',
        'original' => 'Über einige neurotische Mechanismen bei Eifersucht, Paranoia und Homosexualität',
        'ano' => '1922',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Projeção', 'Paranoia', 'Ciúme'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Notas Psicanalíticas sobre um Relato Autobiográfico de um Caso de Paranoia (Caso Schreber)'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Dois Verbetes de Enciclopédia: Psicanálise e Teoria da Libido',
        'original' => 'Zwei Enzyklopädie-Artikel: Psychoanalyse und Libidotheorie',
        'ano' => '1923',
        'idioma' => 'Alemão',
        'tipo' => 'Artigo Técnico',
        'area' => 'Freud',
        'conceitos' => ['Definição de psicanálise', 'Libido'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'O Ego e o Id',
        'original' => 'Das Ich und das Es',
        'ano' => '1923',
        'idioma' => 'Alemão',
        'tipo' => 'Livro',
        'area' => 'Freud',
        'conceitos' => ['Segunda tópica', 'Id', 'Ego', 'Superego'],
        'autores_relacionados' => ['Jacques Lacan'],
        'obras_relacionadas' => ['Sobre o Narcisismo: uma Introdução', 'Luto e Melancolia'],
        'motores' => [FE, LE],
        'status' => 'Catalogado',
        'observacoes' => 'Formula a segunda tópica (id/ego/superego); base necessária, ainda que não citada nominalmente em Ontologia-Freud.md §6, para a articulação do registro Simbólico em Lacan.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Uma Neurose Demoníaca no Século XVII',
        'original' => 'Eine Teufelsneurose im siebzehnten Jahrhundert',
        'ano' => '1923',
        'idioma' => 'Alemão',
        'tipo' => 'Caso Clínico',
        'area' => 'Freud',
        'conceitos' => ['Neurose', 'Pacto demoníaco como formação substitutiva'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'O Problema Econômico do Masoquismo',
        'original' => 'Das ökonomische Problem des Masochismus',
        'ano' => '1924',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Masoquismo', 'Pulsão de morte', 'Culpa inconsciente'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Além do Princípio do Prazer', 'Uma Criança é Espancada'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'A Dissolução do Complexo de Édipo',
        'original' => 'Der Untergang des Ödipuskomplexes',
        'ano' => '1924',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Complexo de Édipo', 'Angústia de castração'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Análise de uma Fobia em um Menino de Cinco Anos (Caso Pequeno Hans)'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Neurose e Psicose',
        'original' => 'Neurose und Psychose',
        'ano' => '1924',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Neurose', 'Psicose', 'Realidade'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['A Perda da Realidade na Neurose e na Psicose'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'A Perda da Realidade na Neurose e na Psicose',
        'original' => 'Der Realitätsverlust bei Neurose und Psychose',
        'ano' => '1924',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Neurose', 'Psicose', 'Realidade'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Neurose e Psicose'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Um Estudo Autobiográfico',
        'original' => 'Selbstdarstellung',
        'ano' => '1925',
        'idioma' => 'Alemão',
        'tipo' => 'Livro',
        'area' => 'Freud',
        'conceitos' => ['História da psicanálise'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['A História do Movimento Psicanalítico'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Negação',
        'original' => 'Die Verneinung',
        'ano' => '1925',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Negação', 'Julgamento', 'Recalque'],
        'autores_relacionados' => ['Jacques Lacan'],
        'obras_relacionadas' => ['A Repressão (O Recalque)'],
        'motores' => [FE, LE],
        'status' => 'Catalogado',
        'observacoes' => 'Um dos textos freudianos mais centrais para Lacan (comentado extensamente em seminário); ainda não citado nominalmente em Ontologia-Freud.md §6, mas incluído aqui pelo cruzamento estrutural amplamente documentado.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => "Nota sobre o 'Bloco Mágico'",
        'original' => "Notiz über den 'Wunderblock'",
        'ano' => '1925',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Memória', 'Aparelho psíquico', 'Traço mnêmico'],
        'autores_relacionados' => ['Jacques Derrida'],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Algumas Consequências Psíquicas da Distinção Anatômica entre os Sexos',
        'original' => 'Einige psychische Folgen des anatomischen Geschlechtsunterschieds',
        'ano' => '1925',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Diferença sexual', 'Complexo de Édipo', 'Inveja do pênis'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Sobre a Sexualidade Feminina'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Resistências à Psicanálise',
        'original' => 'Die Widerstände gegen die Psychoanalyse',
        'ano' => '1925',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Resistência'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Inibições, Sintomas e Ansiedade',
        'original' => 'Hemmung, Symptom und Angst',
        'ano' => '1926',
        'idioma' => 'Alemão',
        'tipo' => 'Livro',
        'area' => 'Freud',
        'conceitos' => ['Angústia', 'Sintoma', 'Inibição', 'Sinal de angústia'],
        'autores_relacionados' => ['Jacques Lacan'],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Reformulação da teoria da angústia; base para o Seminário X de Lacan.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'A Questão da Análise Leiga',
        'original' => 'Die Frage der Laienanalyse',
        'ano' => '1926',
        'idioma' => 'Alemão',
        'tipo' => 'Livro',
        'area' => 'Freud',
        'conceitos' => ['Formação do analista', 'Prática não médica da psicanálise'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'O Futuro de uma Ilusão',
        'original' => 'Die Zukunft einer Illusion',
        'ano' => '1927',
        'idioma' => 'Alemão',
        'tipo' => 'Livro',
        'area' => 'Freud',
        'conceitos' => ['Religião como ilusão', 'Civilização'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Mal-estar na Civilização'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'O Humor',
        'original' => 'Der Humor',
        'ano' => '1927',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Humor', 'Superego'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Os Chistes e sua Relação com o Inconsciente'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Fetichismo',
        'original' => 'Fetischismus',
        'ano' => '1927',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Fetichismo', 'Recusa (Verleugnung)', 'Angústia de castração'],
        'autores_relacionados' => ['Jacques Lacan'],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Introduz o mecanismo de recusa (Verleugnung), retomado por Lacan na leitura da foraclusão e da psicose.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Dostoiévski e o Parricídio',
        'original' => 'Dostojewski und die Vatertötung',
        'ano' => '1928',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Culpa inconsciente', 'Ambivalência', 'Complexo de Édipo'],
        'autores_relacionados' => ['Fiódor Dostoiévski'],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Mal-estar na Civilização',
        'original' => 'Das Unbehagen in der Kultur',
        'ano' => '1930',
        'idioma' => 'Alemão',
        'tipo' => 'Livro',
        'area' => 'Freud',
        'conceitos' => ['Pulsão de morte', 'Civilização', 'Superego cultural', 'Recalque cultural'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['O Futuro de uma Ilusão', 'Além do Princípio do Prazer'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Uma das últimas grandes obras de síntese teórica de Freud.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Sobre a Sexualidade Feminina',
        'original' => 'Über die weibliche Sexualität',
        'ano' => '1931',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Sexualidade feminina', 'Complexo de Édipo', 'Fase pré-edípica'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Algumas Consequências Psíquicas da Distinção Anatômica entre os Sexos'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Novas Conferências Introdutórias sobre Psicanálise',
        'original' => 'Neue Folge der Vorlesungen zur Einführung in die Psychoanalyse',
        'ano' => '1933',
        'idioma' => 'Alemão',
        'tipo' => 'Livro',
        'area' => 'Freud',
        'conceitos' => ['Segunda tópica', 'Feminilidade', 'Angústia'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Conferências Introdutórias sobre Psicanálise'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud (com Albert Einstein)',
        'titulo' => 'Por que a Guerra?',
        'original' => 'Warum Krieg?',
        'ano' => '1933',
        'idioma' => 'Alemão',
        'tipo' => 'Carta',
        'area' => 'Freud',
        'conceitos' => ['Pulsão de morte', 'Agressividade'],
        'autores_relacionados' => ['Albert Einstein'],
        'obras_relacionadas' => ['Além do Princípio do Prazer'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Correspondência aberta trocada com Einstein a pedido da Liga das Nações.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Um Distúrbio de Memória na Acrópole',
        'original' => 'Brief an Romain Rolland: Eine Erinnerungsstörung auf der Akropolis',
        'ano' => '1936',
        'idioma' => 'Alemão',
        'tipo' => 'Carta',
        'area' => 'Freud',
        'conceitos' => ['Estranhamento', 'Culpa inconsciente', 'Memória'],
        'autores_relacionados' => ['Romain Rolland'],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Carta aberta dedicada a Romain Rolland por ocasião de seu septuagésimo aniversário.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Análise Terminável e Interminável',
        'original' => 'Die endliche und die unendliche Analyse',
        'ano' => '1937',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Fim de análise', 'Resistência', 'Pulsão de morte'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Construções em Análise',
        'original' => 'Konstruktionen in der Analyse',
        'ano' => '1937',
        'idioma' => 'Alemão',
        'tipo' => 'Artigo Técnico',
        'area' => 'Freud',
        'conceitos' => ['Construção analítica', 'Técnica psicanalítica'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Moisés e o Monoteísmo',
        'original' => 'Der Mann Moses und die monotheistische Religion',
        'ano' => '1939',
        'idioma' => 'Alemão',
        'tipo' => 'Livro',
        'area' => 'Freud',
        'conceitos' => ['Mito do pai da horda', 'Tradição', 'Retorno do recalcado (cultural)'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Totem e Tabu', 'O Moisés de Michelangelo'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Última obra publicada em vida por Freud.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'Esboço de Psicanálise',
        'original' => 'Abriss der Psychoanalyse',
        'ano' => '1940 (publicado postumamente; redigido em 1938)',
        'idioma' => 'Alemão',
        'tipo' => 'Livro',
        'area' => 'Freud',
        'conceitos' => ['Síntese da teoria psicanalítica', 'Segunda tópica'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Obra de síntese inacabada, publicada postumamente.',
    ],
    [
        'autor' => 'Sigmund Freud',
        'titulo' => 'A Divisão do Ego no Processo de Defesa',
        'original' => 'Die Ichspaltung im Abwehrvorgang',
        'ano' => '1940 (publicado postumamente; redigido em 1938)',
        'idioma' => 'Alemão',
        'tipo' => 'Ensaio',
        'area' => 'Freud',
        'conceitos' => ['Clivagem do ego', 'Recusa (Verleugnung)', 'Fetichismo'],
        'autores_relacionados' => ['Jacques Lacan'],
        'obras_relacionadas' => ['Fetichismo'],
        'motores' => NENHUM,
        'status' => 'Catalogado',
        'observacoes' => 'Último texto teórico de Freud, publicado postumamente; central para a leitura lacaniana da divisão do sujeito ($).',
    ],
];
