<?php
declare(strict_types=1);

/**
 * Dataset — Outros Escritos (Autres écrits, coletânea póstuma organizada
 * por Jacques-Alain Miller, 2001). Reúne textos de Lacan não incluídos em
 * Écrits (1966). Cobertura desta versão é deliberadamente mais cautelosa
 * que a de Écrits: vários itens estão com Status "A verificar" porque a
 * datação/inclusão exata no sumário de 2001 não pôde ser confirmada contra
 * a edição física nesta Sprint — preferível a apresentar falsa precisão.
 */

const NENHUM3 = ['Nenhum (catalogação apenas)'];
const LE3 = 'Lacan Engine';

return [
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Discurso de Roma',
        'original' => 'Discours de Rome',
        'ano' => '1953',
        'idioma' => 'Francês',
        'tipo' => 'Conferência',
        'area' => 'Lacan',
        'conceitos' => ['Palavra plena', 'Registro Simbólico'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Função e Campo da Palavra e da Linguagem em Psicanálise'],
        'motores' => NENHUM3,
        'status' => 'Catalogado',
        'observacoes' => 'Versão preliminar/discurso de abertura distinto de "Fonction et champ de la parole et du langage", que foi publicado em Écrits.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Proposição de 9 de Outubro de 1967 sobre o Psicanalista da Escola',
        'original' => 'Proposition du 9 octobre 1967 sur le psychanalyste de l\'École',
        'ano' => '1967',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Passe', 'Formação do analista', 'Escola'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM3,
        'status' => 'Catalogado',
        'observacoes' => 'Institui o dispositivo do passe na École Freudienne de Paris.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Do Sujeito Enfim em Questão',
        'original' => 'Du sujet enfin en question',
        'ano' => '1966',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Sujeito'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM3,
        'status' => 'A verificar',
        'observacoes' => 'Data e contexto de publicação a confirmar.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Alocução sobre as Psicoses da Criança',
        'original' => "Allocution sur les psychoses de l'enfant",
        'ano' => '1967',
        'idioma' => 'Francês',
        'tipo' => 'Conferência',
        'area' => 'Lacan',
        'conceitos' => ['Psicose', 'Infância'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM3,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Nota sobre a Criança',
        'original' => "Note sur l'enfant",
        'ano' => '1969',
        'idioma' => 'Francês',
        'tipo' => 'Carta',
        'area' => 'Lacan',
        'conceitos' => ['Infância', 'Sintoma'],
        'autores_relacionados' => ['Françoise Dolto'],
        'obras_relacionadas' => [],
        'motores' => NENHUM3,
        'status' => 'Catalogado',
        'observacoes' => 'Carta dirigida a Jenny Aubry.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Radiofonia',
        'original' => 'Radiophonie',
        'ano' => '1970',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Significante', 'Discurso'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM3,
        'status' => 'Catalogado',
        'observacoes' => 'Entrevista/ensaio em forma de perguntas e respostas, transmitido pela rádio belga.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Lituraterra',
        'original' => 'Lituraterre',
        'ano' => '1971',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Letra', 'Escrita', 'Registro Real'],
        'autores_relacionados' => ['James Joyce'],
        'obras_relacionadas' => [],
        'motores' => NENHUM3,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'O Aturdito',
        'original' => "L'étourdit",
        'ano' => '1972',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Dito e dizer', 'Lógica', 'Não-todo'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM3,
        'status' => 'Catalogado',
        'observacoes' => 'Um dos textos mais formalizados/lógicos de Lacan, contemporâneo ao Seminário XIX.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Nota Italiana',
        'original' => 'Note italienne',
        'ano' => '1973',
        'idioma' => 'Francês',
        'tipo' => 'Carta',
        'area' => 'Lacan',
        'conceitos' => ['Formação do analista', 'Passe'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Proposição de 9 de Outubro de 1967 sobre o Psicanalista da Escola'],
        'motores' => NENHUM3,
        'status' => 'Catalogado',
        'observacoes' => 'Dirigida aos psicanalistas italianos por ocasião da fundação da Scuola Freudiana.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Televisão',
        'original' => 'Télévision',
        'ano' => '1973',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Discurso', 'Gozo', 'Verdade'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM3,
        'status' => 'Catalogado',
        'observacoes' => 'Entrevista concedida à televisão francesa (ORTF), posteriormente publicada em livro.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'A Terceira',
        'original' => 'La Troisième',
        'ano' => '1974',
        'idioma' => 'Francês',
        'tipo' => 'Conferência',
        'area' => 'Lacan',
        'conceitos' => ['Registro Real', 'Sintoma', 'Nós Borromeanos'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM3,
        'status' => 'Catalogado',
        'observacoes' => 'Apresentada no Congresso de Roma da Escola Freudiana de Paris.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Talvez em Vincennes...',
        'original' => 'Peut-être à Vincennes...',
        'ano' => '1975',
        'idioma' => 'Francês',
        'tipo' => 'Carta',
        'area' => 'Lacan',
        'conceitos' => ['Formação do analista', 'Universidade'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM3,
        'status' => 'A verificar',
        'observacoes' => 'Carta curta sobre o ensino da psicanálise na universidade de Vincennes; datação a confirmar.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Conferência de Genebra sobre o Sintoma',
        'original' => 'Conférence de Genève sur le symptôme',
        'ano' => '1975',
        'idioma' => 'Francês',
        'tipo' => 'Conferência',
        'area' => 'Lacan',
        'conceitos' => ['Sintoma', 'Gozo'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['O Sinthoma (Seminário XXIII)'],
        'motores' => NENHUM3,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Prefácio à Edição Inglesa do Seminário XI',
        'original' => 'Preface to the English edition of Seminar XI',
        'ano' => '1976',
        'idioma' => 'Inglês',
        'tipo' => 'Prefácio',
        'area' => 'Lacan',
        'conceitos' => ['Inconsciente', 'Repetição'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Os Quatro Conceitos Fundamentais da Psicanálise (Seminário XI)'],
        'motores' => NENHUM3,
        'status' => 'A verificar',
        'observacoes' => 'Ano de publicação da edição inglesa a confirmar.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Joyce, o Sintoma',
        'original' => 'Joyce le symptôme',
        'ano' => '1979',
        'idioma' => 'Francês',
        'tipo' => 'Conferência',
        'area' => 'Lacan',
        'conceitos' => ['Sintoma', 'Nome-do-Pai', 'Suplência'],
        'autores_relacionados' => ['James Joyce'],
        'obras_relacionadas' => ['O Sinthoma (Seminário XXIII)'],
        'motores' => NENHUM3,
        'status' => 'Catalogado',
        'observacoes' => 'Conferência de abertura do 5º Congresso Internacional James Joyce.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Prefácio a "O Despertar da Primavera", de Frank Wedekind',
        'original' => "Préface à L'Éveil du printemps",
        'ano' => '1974',
        'idioma' => 'Francês',
        'tipo' => 'Prefácio',
        'area' => 'Lacan',
        'conceitos' => ['Sexualidade infantil'],
        'autores_relacionados' => ['Frank Wedekind'],
        'obras_relacionadas' => [],
        'motores' => NENHUM3,
        'status' => 'A verificar',
        'observacoes' => 'Ano de composição a confirmar.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Resumo do Seminário sobre a Ética da Psicanálise',
        'original' => "Compte rendu du Séminaire de l'éthique",
        'ano' => '1967',
        'idioma' => 'Francês',
        'tipo' => 'Artigo Técnico',
        'area' => 'Lacan',
        'conceitos' => ['Ética', 'Desejo lacaniano'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['A Ética da Psicanálise (Seminário VII)'],
        'motores' => NENHUM3,
        'status' => 'A verificar',
        'observacoes' => 'Resumo do Seminário VII publicado no Annuaire de l\'École Pratique des Hautes Études; ano de publicação a confirmar.',
    ],
];
