<?php
declare(strict_types=1);

/**
 * Dataset — Escritos (Écrits, 1966) de Jacques Lacan. Datas referem-se à
 * redação/apresentação original de cada texto, não à data de 1966 da
 * coletânea (registrada nas Observações de cada entrada).
 */

const FE2 = 'Freud Engine';
const LE2 = 'Lacan Engine';
const NENHUM2 = ['Nenhum (catalogação apenas)'];

return [
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Além do «Princípio de Realidade»',
        'original' => 'Au-delà du «principe de réalité»',
        'ano' => '1936',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Princípio de realidade', 'Crítica à psicologia associacionista'],
        'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => [],
        'motores' => NENHUM2,
        'status' => 'Catalogado',
        'observacoes' => 'Texto de abertura de Écrits (1966), primeiro trabalho publicado de Lacan reunido na coletânea.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'O Estádio do Espelho como Formador da Função do Eu',
        'original' => "Le stade du miroir comme formateur de la fonction du Je",
        'ano' => '1949 (apresentado em 1936 e 1949)',
        'idioma' => 'Francês',
        'tipo' => 'Conferência',
        'area' => 'Lacan',
        'conceitos' => ['Estádio do espelho', 'Registro Imaginário', 'Eu (moi)'],
        'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => ['Sobre o Narcisismo: uma Introdução'],
        'motores' => NENHUM2,
        'status' => 'Catalogado',
        'observacoes' => 'Apresentado no XVI Congresso Internacional de Psicanálise (Zurique, 1949); versão de 1936 não sobrevive.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'A Agressividade em Psicanálise',
        'original' => "L'agressivité en psychanalyse",
        'ano' => '1948',
        'idioma' => 'Francês',
        'tipo' => 'Conferência',
        'area' => 'Lacan',
        'conceitos' => ['Agressividade', 'Registro Imaginário', 'Identificação'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['O Estádio do Espelho como Formador da Função do Eu'],
        'motores' => NENHUM2,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Função e Campo da Palavra e da Linguagem em Psicanálise',
        'original' => 'Fonction et champ de la parole et du langage en psychanalyse',
        'ano' => '1953',
        'idioma' => 'Francês',
        'tipo' => 'Conferência',
        'area' => 'Lacan',
        'conceitos' => ['Palavra plena', 'Palavra vazia', 'Linguagem', 'Registro Simbólico'],
        'autores_relacionados' => ['Ferdinand de Saussure', 'Claude Lévi-Strauss'],
        'obras_relacionadas' => [],
        'motores' => [LE2],
        'status' => 'Catalogado',
        'observacoes' => 'Conhecido como "Rapport de Rome"; um dos textos fundadores do chamado "retorno a Freud".',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'O Seminário sobre "A Carta Roubada"',
        'original' => "Le séminaire sur «La Lettre volée»",
        'ano' => '1956 (redigido em 1956, publicado como abertura de Écrits em 1966)',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Cadeia significante', 'Repetição automática', 'Circulação do significante'],
        'autores_relacionados' => ['Edgar Allan Poe'],
        'obras_relacionadas' => [],
        'motores' => [LE2],
        'status' => 'Catalogado',
        'observacoes' => 'Comentário sobre o conto "A Carta Roubada", de Edgar Allan Poe; abre a edição de 1966 dos Écrits.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Introdução e Resposta ao Comentário de Jean Hyppolite sobre a "Verneinung" de Freud',
        'original' => "Introduction et réponse au commentaire de Jean Hyppolite sur la « Verneinung » de Freud",
        'ano' => '1954',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Negação', 'Registro Simbólico'],
        'autores_relacionados' => ['Jean Hyppolite', 'Sigmund Freud'],
        'obras_relacionadas' => ['Negação'],
        'motores' => [LE2],
        'status' => 'Catalogado',
        'observacoes' => 'Comentário ao texto de Freud "Die Verneinung" (1925), com resposta ao filósofo Jean Hyppolite.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'A Coisa Freudiana',
        'original' => 'La chose freudienne',
        'ano' => '1955',
        'idioma' => 'Francês',
        'tipo' => 'Conferência',
        'area' => 'Lacan',
        'conceitos' => ['Retorno a Freud', 'Verdade', 'Inconsciente estruturado como linguagem'],
        'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => [],
        'motores' => NENHUM2,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Variantes da Cura-Padrão',
        'original' => 'Variantes de la cure-type',
        'ano' => '1955',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Técnica psicanalítica', 'Cura-tipo'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM2,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'A Instância da Letra no Inconsciente ou a Razão desde Freud',
        'original' => "L'instance de la lettre dans l'inconscient ou la raison depuis Freud",
        'ano' => '1957',
        'idioma' => 'Francês',
        'tipo' => 'Conferência',
        'area' => 'Lacan',
        'conceitos' => ['Significante', 'Cadeia significante', 'Metáfora', 'Metonímia'],
        'autores_relacionados' => ['Ferdinand de Saussure', 'Roman Jakobson'],
        'obras_relacionadas' => ['A Interpretação dos Sonhos', 'Os Chistes e sua Relação com o Inconsciente'],
        'motores' => [LE2],
        'status' => 'Catalogado',
        'observacoes' => 'Um dos textos centrais para a leitura estrutural de condensação/deslocamento como metáfora/metonímia, citada em Ontologia-Lacan.md.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'D\'uma Questão Preliminar a Todo Tratamento Possível da Psicose',
        'original' => "D'une question préliminaire à tout traitement possible de la psychose",
        'ano' => '1958',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Psicose', 'Foraclusão', 'Nome-do-Pai'],
        'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => ['Notas Psicanalíticas sobre um Relato Autobiográfico de um Caso de Paranoia (Caso Schreber)'],
        'motores' => NENHUM2,
        'status' => 'Catalogado',
        'observacoes' => 'Retoma o caso Schreber de Freud; introduz o conceito de foraclusão do Nome-do-Pai.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'A Direção do Tratamento e os Princípios de seu Poder',
        'original' => 'La direction de la cure et les principes de son pouvoir',
        'ano' => '1958',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Direção do tratamento', 'Desejo do analista'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM2,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'A Significação do Falo',
        'original' => 'La signification du phallus (Die Bedeutung des Phallus)',
        'ano' => '1958',
        'idioma' => 'Francês/Alemão',
        'tipo' => 'Conferência',
        'area' => 'Lacan',
        'conceitos' => ['Falo', 'Falta', 'Desejo lacaniano'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => [LE2],
        'status' => 'Catalogado',
        'observacoes' => 'Conferência proferida em Munique, publicada em francês e alemão.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Propostas Diretivas para um Congresso sobre a Sexualidade Feminina',
        'original' => 'Propos directifs pour un congrès sur la sexualité féminine',
        'ano' => '1958',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Sexualidade feminina', 'Falo'],
        'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => ['Sobre a Sexualidade Feminina'],
        'motores' => NENHUM2,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Juventude de Gide, ou a Letra e o Desejo',
        'original' => "Jeunesse de Gide, ou la lettre et le désir",
        'ano' => '1958',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Letra', 'Desejo lacaniano'],
        'autores_relacionados' => ['André Gide'],
        'obras_relacionadas' => [],
        'motores' => NENHUM2,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'A Psicanálise e seu Ensino',
        'original' => 'La psychanalyse et son enseignement',
        'ano' => '1957',
        'idioma' => 'Francês',
        'tipo' => 'Conferência',
        'area' => 'Lacan',
        'conceitos' => ['Formação do analista', 'Retorno a Freud'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM2,
        'status' => 'A verificar',
        'observacoes' => 'Data de apresentação a confirmar contra a edição de referência.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'À Memória de Ernest Jones: Sobre sua Teoria do Simbolismo',
        'original' => 'À la mémoire d\'Ernest Jones : sur sa théorie du symbolisme',
        'ano' => '1959',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Simbolismo', 'Registro Simbólico'],
        'autores_relacionados' => ['Ernest Jones'],
        'obras_relacionadas' => [],
        'motores' => NENHUM2,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Observação sobre o Relatório de Daniel Lagache',
        'original' => 'Remarque sur le rapport de Daniel Lagache',
        'ano' => '1960',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Sujeito', 'Eu (moi)'],
        'autores_relacionados' => ['Daniel Lagache'],
        'obras_relacionadas' => [],
        'motores' => NENHUM2,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Subversão do Sujeito e Dialética do Desejo no Inconsciente Freudiano',
        'original' => "Subversion du sujet et dialectique du désir dans l'inconscient freudien",
        'ano' => '1960',
        'idioma' => 'Francês',
        'tipo' => 'Conferência',
        'area' => 'Lacan',
        'conceitos' => ['Sujeito', 'Desejo lacaniano', 'Outro', 'Objeto a'],
        'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => [],
        'motores' => [LE2],
        'status' => 'Catalogado',
        'observacoes' => 'Introduz a formulação gráfica do desejo, precursora do Grafo do Desejo — ver Roadmap.md "Sprints futuras" (Grafo do Desejo, ainda sem base ontológica computacional).',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Posição do Inconsciente',
        'original' => "Position de l'inconscient",
        'ano' => '1960 (revisado em 1964)',
        'idioma' => 'Francês',
        'tipo' => 'Conferência',
        'area' => 'Lacan',
        'conceitos' => ['Inconsciente', 'Registro Simbólico', 'Sujeito'],
        'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => ['O Inconsciente'],
        'motores' => [LE2],
        'status' => 'Catalogado',
        'observacoes' => 'Apresentado no Colóquio de Bonneval (1960); revisado após o Seminário XI (1964).',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Kant com Sade',
        'original' => 'Kant avec Sade',
        'ano' => '1963',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Ética', 'Gozo', 'Lei'],
        'autores_relacionados' => ['Immanuel Kant', 'Marquês de Sade'],
        'obras_relacionadas' => [],
        'motores' => NENHUM2,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Ciência e Verdade',
        'original' => 'Science et vérité',
        'ano' => '1965',
        'idioma' => 'Francês',
        'tipo' => 'Conferência',
        'area' => 'Lacan',
        'conceitos' => ['Sujeito da ciência', 'Verdade', 'Causa'],
        'autores_relacionados' => ['Alexandre Koyré'],
        'obras_relacionadas' => [],
        'motores' => NENHUM2,
        'status' => 'Catalogado',
        'observacoes' => 'Texto de encerramento de Écrits (1966).',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'O Tempo Lógico e a Asserção de Certeza Antecipada',
        'original' => "Le temps logique et l'assertion de certitude anticipée",
        'ano' => '1945',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Tempo lógico', 'Certeza antecipada', 'Sujeito'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM2,
        'status' => 'Catalogado',
        'observacoes' => 'Conhecido pelo "sofisma dos três prisioneiros".',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'A Coisa Psicanalítica: Verdadeira e Falsa (A Psicanálise Verdadeira e a Falsa)',
        'original' => 'La psychanalyse vraie, et la fausse',
        'ano' => '1958',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Formação do analista'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM2,
        'status' => 'A verificar',
        'observacoes' => 'Inclusão nesta versão dos Écrits e datação exatas a confirmar contra o sumário oficial da edição de 1966.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Situação da Psicanálise e Formação do Psicanalista em 1956',
        'original' => 'Situation de la psychanalyse et formation du psychanalyste en 1956',
        'ano' => '1956',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Formação do analista', 'Retorno a Freud'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM2,
        'status' => 'Catalogado',
        'observacoes' => '',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Variantes da Cura-Padrão — Apresentação',
        'original' => "D'un dessein",
        'ano' => '1966',
        'idioma' => 'Francês',
        'tipo' => 'Prefácio',
        'area' => 'Lacan',
        'conceitos' => ['Apresentação editorial'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM2,
        'status' => 'A verificar',
        'observacoes' => 'Texto curto de abertura escrito para a coletânea de 1966; título e posição exatos no sumário a confirmar.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'De Nossos Antecedentes',
        'original' => 'De nos antécédents',
        'ano' => '1966',
        'idioma' => 'Francês',
        'tipo' => 'Prefácio',
        'area' => 'Lacan',
        'conceitos' => ['Apresentação editorial', 'Retorno a Freud'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM2,
        'status' => 'Catalogado',
        'observacoes' => 'Texto retrospectivo escrito para a coletânea de 1966, situando os textos anteriores a 1953.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Abertura desta Coletânea',
        'original' => 'Ouverture de ce recueil',
        'ano' => '1966',
        'idioma' => 'Francês',
        'tipo' => 'Prefácio',
        'area' => 'Lacan',
        'conceitos' => ['Estilo', 'Escrita'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM2,
        'status' => 'Catalogado',
        'observacoes' => 'Texto de abertura de Écrits (1966), sobre a dificuldade proposital do estilo lacaniano.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'A Ciência e a Verdade — Sobre a Causalidade Psíquica',
        'original' => 'Propos sur la causalité psychique',
        'ano' => '1946',
        'idioma' => 'Francês',
        'tipo' => 'Conferência',
        'area' => 'Lacan',
        'conceitos' => ['Causalidade psíquica', 'Loucura'],
        'autores_relacionados' => ['Henri Ey'],
        'obras_relacionadas' => [],
        'motores' => NENHUM2,
        'status' => 'Catalogado',
        'observacoes' => 'Apresentado nas Journées Psychiatriques de Bonneval (1946), em debate com Henri Ey.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Formulações sobre a Causalidade Psíquica',
        'original' => 'De nos antécédents (nota complementar)',
        'ano' => '1946',
        'idioma' => 'Francês',
        'tipo' => 'Ensaio',
        'area' => 'Lacan',
        'conceitos' => ['Causalidade psíquica'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['A Ciência e a Verdade — Sobre a Causalidade Psíquica'],
        'motores' => NENHUM2,
        'status' => 'A verificar',
        'observacoes' => 'Entrada mantida por cautela editorial; pode duplicar a entrada anterior — a confirmar e, se confirmada duplicidade, remover em revisão futura desta Sprint.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'A Psiquiatria Inglesa e a Guerra',
        'original' => "La psychiatrie anglaise et la guerre",
        'ano' => '1947',
        'idioma' => 'Francês',
        'tipo' => 'Artigo',
        'area' => 'Lacan',
        'conceitos' => ['Psiquiatria institucional'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM2,
        'status' => 'A verificar',
        'observacoes' => 'Reportagem/ensaio sobre a psiquiatria britânica no pós-guerra; nem sempre incluído nas edições de Écrits — a confirmar se compõe o sumário de 1966 ou se é um texto avulso do mesmo período.',
    ],
];
