<?php
declare(strict_types=1);

/**
 * Dataset — O Seminário (Le Séminaire), 27 anos letivos ministrados por
 * Jacques Lacan (1953-1980). "Status" distingue volumes estabelecidos e
 * publicados oficialmente por Jacques-Alain Miller (Catalogado) dos que
 * circulam apenas em versões não oficiais/estabelecidas por terceiros
 * (A verificar — não há edição crítica de referência a citar ainda).
 */

const NENHUM4 = ['Nenhum (catalogação apenas)'];
const LE4 = 'Lacan Engine';

return [
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Os Escritos Técnicos de Freud (Seminário I)',
        'original' => 'Les écrits techniques de Freud',
        'ano' => '1953–1954',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Técnica psicanalítica freudiana', 'Retorno a Freud'],
        'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => [],
        'motores' => NENHUM4,
        'status' => 'Catalogado',
        'observacoes' => 'Primeiro ano do Seminário; estabelecido e publicado por Jacques-Alain Miller (Éditions du Seuil, 1975).',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'O Eu na Teoria de Freud e na Técnica da Psicanálise (Seminário II)',
        'original' => "Le moi dans la théorie de Freud et dans la technique de la psychanalyse",
        'ano' => '1954–1955',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Eu (moi)', 'Registro Imaginário', 'Registro Simbólico'],
        'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => ['O Ego e o Id'],
        'motores' => NENHUM4,
        'status' => 'Catalogado',
        'observacoes' => 'Publicado por Jacques-Alain Miller (Éditions du Seuil, 1978).',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'As Psicoses (Seminário III)',
        'original' => 'Les psychoses',
        'ano' => '1955–1956',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Psicose', 'Foraclusão', 'Significante'],
        'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => ['Notas Psicanalíticas sobre um Relato Autobiográfico de um Caso de Paranoia (Caso Schreber)', "D'uma Questão Preliminar a Todo Tratamento Possível da Psicose"],
        'motores' => NENHUM4,
        'status' => 'Catalogado',
        'observacoes' => 'Publicado por Jacques-Alain Miller (Éditions du Seuil, 1981).',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'A Relação de Objeto (Seminário IV)',
        'original' => "La relation d'objet",
        'ano' => '1956–1957',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Relação de objeto', 'Falta', 'Falo'],
        'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => [],
        'motores' => NENHUM4,
        'status' => 'Catalogado',
        'observacoes' => 'Publicado por Jacques-Alain Miller (Éditions du Seuil, 1994).',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'As Formações do Inconsciente (Seminário V)',
        'original' => "Les formations de l'inconscient",
        'ano' => '1957–1958',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Formação de compromisso', 'Chiste', 'Metáfora', 'Metonímia'],
        'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => ['Os Chistes e sua Relação com o Inconsciente', 'Psicopatologia da Vida Cotidiana'],
        'motores' => [LE4],
        'status' => 'Catalogado',
        'observacoes' => 'Publicado por Jacques-Alain Miller (Éditions du Seuil, 1998); leitura estrutural das formações do inconsciente freudianas — chiste, ato falho, sintoma.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'O Desejo e sua Interpretação (Seminário VI)',
        'original' => "Le désir et son interprétation",
        'ano' => '1958–1959',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Desejo lacaniano', 'Fantasia', 'Grafo do Desejo'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['Subversão do Sujeito e Dialética do Desejo no Inconsciente Freudiano'],
        'motores' => NENHUM4,
        'status' => 'Catalogado',
        'observacoes' => 'Publicado por Éditions de La Martinière/Le Champ freudien, 2013 — publicação mais tardia entre os seminários oficiais.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'A Ética da Psicanálise (Seminário VII)',
        'original' => 'L\'éthique de la psychanalyse',
        'ano' => '1959–1960',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Ética', 'Das Ding', 'Gozo'],
        'autores_relacionados' => ['Immanuel Kant', 'Sófocles'],
        'obras_relacionadas' => [],
        'motores' => NENHUM4,
        'status' => 'Catalogado',
        'observacoes' => 'Publicado por Jacques-Alain Miller (Éditions du Seuil, 1986); leitura de Antígona, de Sófocles.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'A Transferência (Seminário VIII)',
        'original' => 'Le transfert',
        'ano' => '1960–1961',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Transferência', 'Objeto a', 'Amor'],
        'autores_relacionados' => ['Platão', 'Sigmund Freud'],
        'obras_relacionadas' => ['A Dinâmica da Transferência'],
        'motores' => NENHUM4,
        'status' => 'Catalogado',
        'observacoes' => 'Publicado por Jacques-Alain Miller (Éditions du Seuil, 1991); leitura de O Banquete, de Platão.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'A Identificação (Seminário IX)',
        'original' => "L'identification",
        'ano' => '1961–1962',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Identificação', 'Traço unário'],
        'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => ['Psicologia de Grupo e Análise do Ego'],
        'motores' => NENHUM4,
        'status' => 'A verificar',
        'observacoes' => 'Sem edição oficial estabelecida por Jacques-Alain Miller até esta versão da Biblioteca; circula em versões não oficiais.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'A Angústia (Seminário X)',
        'original' => "L'angoisse",
        'ano' => '1962–1963',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Angústia', 'Objeto a', 'Falta'],
        'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => ['Inibições, Sintomas e Ansiedade'],
        'motores' => NENHUM4,
        'status' => 'Catalogado',
        'observacoes' => 'Publicado por Jacques-Alain Miller (Éditions du Seuil, 2004).',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Os Quatro Conceitos Fundamentais da Psicanálise (Seminário XI)',
        'original' => 'Les quatre concepts fondamentaux de la psychanalyse',
        'ano' => '1964',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Inconsciente', 'Repetição', 'Transferência', 'Pulsão'],
        'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => ['Além do Princípio do Prazer', 'O Inconsciente'],
        'motores' => [LE4],
        'status' => 'Catalogado',
        'observacoes' => 'Publicado por Jacques-Alain Miller (Éditions du Seuil, 1973); um dos volumes mais centrais para a articulação Freud–Lacan citada em Ontologia-Lacan.md.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Problemas Cruciais para a Psicanálise (Seminário XII)',
        'original' => 'Problèmes cruciaux pour la psychanalyse',
        'ano' => '1964–1965',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Sujeito', 'Ciência'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM4,
        'status' => 'A verificar',
        'observacoes' => 'Sem edição oficial estabelecida por Jacques-Alain Miller até esta versão da Biblioteca.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'O Objeto da Psicanálise (Seminário XIII)',
        'original' => "L'objet de la psychanalyse",
        'ano' => '1965–1966',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Objeto a', 'Ciência da lógica'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM4,
        'status' => 'A verificar',
        'observacoes' => 'Sem edição oficial estabelecida por Jacques-Alain Miller até esta versão da Biblioteca.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'A Lógica da Fantasia (Seminário XIV)',
        'original' => 'La logique du fantasme',
        'ano' => '1966–1967',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Fantasia', 'Objeto a', 'Lógica'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM4,
        'status' => 'A verificar',
        'observacoes' => 'Sem edição oficial estabelecida por Jacques-Alain Miller até esta versão da Biblioteca.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'O Ato Psicanalítico (Seminário XV)',
        'original' => "L'acte psychanalytique",
        'ano' => '1967–1968',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Ato', 'Desejo do analista'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM4,
        'status' => 'A verificar',
        'observacoes' => 'Sem edição oficial estabelecida por Jacques-Alain Miller até esta versão da Biblioteca.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'De um Outro ao outro (Seminário XVI)',
        'original' => "D'un Autre à l'autre",
        'ano' => '1968–1969',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Outro', 'Mais-de-gozar'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM4,
        'status' => 'Catalogado',
        'observacoes' => 'Publicado por Jacques-Alain Miller (Éditions du Seuil, 2006).',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'O Avesso da Psicanálise (Seminário XVII)',
        'original' => 'L\'envers de la psychanalyse',
        'ano' => '1969–1970',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Quatro discursos', 'Mais-de-gozar', 'Laço social'],
        'autores_relacionados' => ['Sigmund Freud'],
        'obras_relacionadas' => ['Totem e Tabu'],
        'motores' => NENHUM4,
        'status' => 'Catalogado',
        'observacoes' => 'Publicado por Jacques-Alain Miller (Éditions du Seuil, 1991); formaliza os quatro discursos — ver Roadmap.md "Sprints futuras" (Quatro discursos lacanianos, ainda sem base ontológica computacional).',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'De um Discurso que Não Seria do Semblante (Seminário XVIII)',
        'original' => "D'un discours qui ne serait pas du semblant",
        'ano' => '1970–1971',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Semblante', 'Discurso'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['O Avesso da Psicanálise (Seminário XVII)'],
        'motores' => NENHUM4,
        'status' => 'Catalogado',
        'observacoes' => 'Publicado por Jacques-Alain Miller (Éditions du Seuil, 2006).',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => '...ou Pior (Seminário XIX)',
        'original' => '...ou pire',
        'ano' => '1971–1972',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Não-todo', 'Lógica'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['O Aturdito'],
        'motores' => NENHUM4,
        'status' => 'Catalogado',
        'observacoes' => 'Publicado por Jacques-Alain Miller (Éditions du Seuil, 2011).',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Mais, Ainda (Seminário XX)',
        'original' => 'Encore',
        'ano' => '1972–1973',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Gozo', 'Não-todo', 'Amor', 'Fórmulas da sexuação'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM4,
        'status' => 'Catalogado',
        'observacoes' => 'Publicado por Jacques-Alain Miller (Éditions du Seuil, 1975); um dos seminários mais citados na recepção contemporânea de Lacan.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Os Não-Tolos Erram (Seminário XXI)',
        'original' => 'Les non-dupes errent',
        'ano' => '1973–1974',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Nome-do-Pai', 'Real'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM4,
        'status' => 'A verificar',
        'observacoes' => 'Sem edição oficial estabelecida por Jacques-Alain Miller até esta versão da Biblioteca; circula em versões não oficiais.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'R.S.I. (Seminário XXII)',
        'original' => 'R.S.I.',
        'ano' => '1974–1975',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Registro Real', 'Registro Simbólico', 'Registro Imaginário', 'Nós Borromeanos'],
        'autores_relacionados' => [],
        'obras_relacionadas' => ['A Terceira'],
        'motores' => NENHUM4,
        'status' => 'A verificar',
        'observacoes' => 'Sem edição oficial estabelecida por Jacques-Alain Miller até esta versão da Biblioteca; circula em versões não oficiais. Central para os Nós Borromeanos — ver Roadmap.md "Sprints futuras".',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'O Sinthoma (Seminário XXIII)',
        'original' => 'Le sinthome',
        'ano' => '1975–1976',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Sinthoma', 'Nós Borromeanos', 'Suplência'],
        'autores_relacionados' => ['James Joyce'],
        'obras_relacionadas' => ['Joyce, o Sintoma'],
        'motores' => NENHUM4,
        'status' => 'Catalogado',
        'observacoes' => 'Publicado por Jacques-Alain Miller (Éditions du Seuil, 2005); leitura da obra de James Joyce.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'O Não-Sabido que Sabe da Uma-Bévue se Ampara na Manhã (Seminário XXIV)',
        'original' => "L'insu que sait de l'une-bévue s'aile à mourre",
        'ano' => '1976–1977',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Equívoco', 'Ato falho'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM4,
        'status' => 'A verificar',
        'observacoes' => 'Título de tradução particularmente instável entre edições (jogo de homofonias intraduzível); sem edição oficial estabelecida por Jacques-Alain Miller até esta versão da Biblioteca.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'O Momento de Concluir (Seminário XXV)',
        'original' => 'Le moment de conclure',
        'ano' => '1977–1978',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Topologia', 'Fim de análise'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM4,
        'status' => 'A verificar',
        'observacoes' => 'Sem edição oficial estabelecida por Jacques-Alain Miller até esta versão da Biblioteca; circula em versões não oficiais.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'A Topologia e o Tempo (Seminário XXVI)',
        'original' => 'La topologie et le temps',
        'ano' => '1978–1979',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Topologia', 'Tempo lógico'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM4,
        'status' => 'A verificar',
        'observacoes' => 'Sem edição oficial estabelecida por Jacques-Alain Miller até esta versão da Biblioteca; circula em versões não oficiais.',
    ],
    [
        'autor' => 'Jacques Lacan',
        'titulo' => 'Dissolução (Seminário XXVII)',
        'original' => 'Dissolution',
        'ano' => '1980',
        'idioma' => 'Francês',
        'tipo' => 'Seminário (Volume)',
        'area' => 'Lacan',
        'conceitos' => ['Escola', 'Dissolução institucional'],
        'autores_relacionados' => [],
        'obras_relacionadas' => [],
        'motores' => NENHUM4,
        'status' => 'A verificar',
        'observacoes' => 'Último ano do Seminário, interrompido pela dissolução da École Freudienne de Paris; sem edição oficial estabelecida por Jacques-Alain Miller até esta versão da Biblioteca.',
    ],
];
